
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(1, 'Gaea\'s Courser', SETS.BROTHERSWAR, true);
collection.addCard(1, 'Gallantry', SETS.TEMPEST);
collection.addCard(1, 'Gallows Warden', SETS.INNISTRAD);
collection.addCard(1, 'Galvanic Arc', SETS.RAVNICACITYOFGUILDS);
collection.addCard(3, 'Galvanic Blast', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Galvanic Juggernaut', SETS.INNISTRAD);
collection.addCard(1, 'Galvanoth', SETS.MIRRODINBESIEGED, true);
collection.addCard(2, 'Gang of Devils', SETS.AVACYNRESTORED);
collection.addCard(1, 'Garruk\'s Companion', SETS.CORE2011);
collection.addCard(3, 'Garruk\'s Companion', SETS.CORE2012);
collection.addCard(1, 'Garruk\'s Horde', SETS.CORE2012);
collection.addCard(1, 'Garruk\'s Packleader', SETS.CORE2013);
collection.addCard(1, 'Gatecreeper Vine', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Gateway Shade', SETS.GATECRASH);
collection.addCard(2, 'Gather the Townsfolk', SETS.BLESSEDVSCURSED);
collection.addCard(5, 'Gather the Townsfolk', SETS.DARKASCENSION);
collection.addCard(1, 'Gatstaf Arsonists', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Gavony Ironwright', SETS.DARKASCENSION);

collection.addCard(1, 'Geier Reach Bandit', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Geist of Saint Traft', SETS.BLESSEDVSCURSED, true);
collection.addCard(1, 'Geist Snatch', SETS.AVACYNRESTORED);
collection.addCard(5, 'Geist Trappers', SETS.AVACYNRESTORED);
collection.addCard(1, 'Geistblast', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Geistflame', SETS.INNISTRAD);
collection.addCard(1, 'Geistflame', SETS.SORINVSINNISTRAD);
collection.addCard(1, 'Gelid Shackles', SETS.COLDSNAP);
collection.addCard(2, 'Gem of Becoming', SETS.CORE2013);
collection.addCard(1, 'Genesis Wave', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Geralf\'s Mindcrusher', SETS.DARKASCENSION);
collection.addCard(1, 'Geth, Thane of Contracts', SETS.ALLWILLBEONE, false, 306);

collection.addCard(4, 'Ghalma\'s Warden', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Ghastly Discovery', SETS.SHADOWMOOR);
collection.addCard(2, 'Ghost Quarter', SETS.INNISTRAD);
collection.addCard(1, 'Ghostly Flicker', SETS.AVACYNRESTORED);
collection.addCard(3, 'Ghostly Possession', SETS.INNISTRAD);
collection.addCard(2, 'Ghostly Touch', SETS.AVACYNRESTORED);
collection.addCard(1, 'Ghostly Wings', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Ghostform', SETS.AVACYNRESTORED);
collection.addCard(4, 'Ghoulcaller\'s Bell', SETS.INNISTRAD);
collection.addCard(4, 'Ghoulcaller\'s Chant', SETS.INNISTRAD);
collection.addCard(4, 'Ghoulflesh', SETS.AVACYNRESTORED);
collection.addCard(2, 'Ghoulraiser', SETS.BLESSEDVSCURSED);
collection.addCard(3, 'Ghoulraiser', SETS.INNISTRAD);
collection.addCard(1, 'Ghoulsteed', SETS.SHADOWSOVERINNISTRAD);

collection.addCard(1, 'Giant Growth', SETS.CORE2011);
collection.addCard(2, 'Giant Growth', SETS.CORE2014);
collection.addCard(1, 'Giant Mantis', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Giant Scorpion', SETS.CORE2013);
collection.addCard(4, 'Giant Spider', SETS.CORE2012);
collection.addCard(1, 'Giant Spider', SETS.CORE2014);
collection.addCard(1, 'Giant Tortoise', SETS.ETERNALMASTERS);
collection.addCard(1, 'Giant\'s Ire', SETS.LORWYN);
collection.addCard(2, 'Gideon\'s Avenger', SETS.CORE2012);
collection.addCard(5, 'Gideon\'s Lawkeeper', SETS.CORE2012);
collection.addCard(2, 'Gideon\'s Reproach', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Gift of Strength', SETS.THEROSBEYONDDEATH);
collection.addCard(5, 'Gift of the Deity', SETS.EVENTIDE);
collection.addCard(1, 'Gigadrowse', SETS.GUILDPACT);
collection.addCard(1, 'Gilt-Leaf Winnower', SETS.MAGICORIGINS);
collection.addCard(1, 'Gitaxian Probe', SETS.NEWPHYREXIA);
collection.addCard(1, 'Gix\'s Caress', SETS.BROTHERSWAR);
collection.addCard(1, 'Gixian Infiltrator', SETS.BROTHERSWAR);

collection.addCard(1, 'Glacial Revelation', SETS.MODERNHORIZONS);
collection.addCard(1, 'Glamer Spinners', SETS.SHADOWMOOR);
collection.addCard(1, 'Glassblower\'s Puzzleknot', SETS.KALADESH);
collection.addCard(1, 'Gleeful Demolition', SETS.ALLWILLBEONE);
collection.addCard(1, 'Glimmerdust Nap', SETS.LORWYN);
collection.addCard(1, 'Glimmerpoint Stag', SETS.SCARSOFMIRRODIN);
collection.addCard(4, 'Glint Hawk', SETS.SCARSOFMIRRODIN);
collection.addCard(2, 'Glissa\'s Courier', SETS.MIRRODINBESIEGED);
collection.addCard(2, 'Glissa\'s Scorn', SETS.NEWPHYREXIA);
collection.addCard(1, 'Glistener Seer', SETS.ALLWILLBEONE);
collection.addCard(1, 'Glitterfang', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(2, 'Gloomwidow', SETS.AVACYNRESTORED);
collection.addCard(1, 'Glorious Charge', SETS.CORE2010);
collection.addCard(2, 'Glorious Charge', SETS.CORE2013);
collection.addCard(1, 'Glory Seeker', SETS.EIGHTH);

collection.addCard(2, 'Gnaw to the Bone', SETS.INNISTRAD);
collection.addCard(1, 'Gnottvold Recluse', SETS.KALDHEIM);

collection.addCard(1, 'Go for the Throat', SETS.BROTHERSWAR);
collection.addCard(1, 'Go for the Throat', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Goat', 't'+SETS.CORE2013, false, 2);
collection.addCard(1, 'Goblin', 't'+SETS.CORE2013, false, 6);
collection.addCard(3, 'Goblin Arsonist', SETS.CORE2013);
collection.addCard(1, 'Goblin Arsonist', SETS.SORINVSINNISTRAD);
collection.addCard(1, 'Goblin Balloon Brigade', SETS.CORE2011);
collection.addCard(5, 'Goblin Battle Jester', SETS.CORE2013);
collection.addCard(6, 'Goblin Brawler', SETS.FIFTHDAWN);
collection.addCard(1, 'Goblin Brigand', SETS.NINTH);
collection.addCard(4, 'Goblin Brigand', SETS.SCOURGE);
collection.addCard(1, 'Goblin Chieftain', SETS.CORE2012);
collection.addCard(1, 'Goblin Diplomats', SETS.MERFOLKVSGOBLINS);
collection.addCard(4, 'Goblin Fireslinger', SETS.CORE2012);
collection.addCard(1, 'Goblin Freerunner', SETS.OATHOFTHEGATEWATCH);
collection.addCard(1, 'Goblin Furrier', SETS.COLDSNAP);
collection.addCard(5, 'Goblin Gaveleer', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Goblin Goon', SETS.MERFOLKVSGOBLINS);
collection.addCard(2, 'Goblin Grenade', SETS.CORE2012);
collection.addCard(1, 'Goblin Mountaineer', SETS.SHARDSOFALARA);
collection.addCard(3, 'Goblin Piker', SETS.CORE2012);
collection.addCard(1, 'Goblin Piker', SETS.CORE2012, true);
collection.addCard(1, 'Goblin Piker', SETS.TENTH);
collection.addCard(4, 'Goblin Raider', SETS.EIGHTH);
collection.addCard(2, 'Goblin Rimerunner', SETS.COLDSNAP);
collection.addCard(2, 'Goblin Shortcutter', SETS.CORE2014);
collection.addCard(1, 'Goblin Sky Raider', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Goblin Sky Raider', SETS.NINTH);
collection.addCard(4, 'Goblin Tunneler', SETS.CORE2012);
collection.addCard(4, 'Goblin War Paint', SETS.CORE2012);
collection.addCard(1, 'Goblin War Paint', SETS.CORE2012, true);
collection.addCard(1, 'Goblin War Party', SETS.MODERNHORIZONS);
collection.addCard(1, 'Gods Willing', SETS.CONSPIRACYTAKETHECROWN);
collection.addCard(2, 'Gold Myr', SETS.SCARSOFMIRRODIN);
collection.addCard(4, 'Golden Urn', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Goldenglow Moth', SETS.CORE2011);
collection.addCard(2, 'Goldnight Commander', SETS.AVACYNRESTORED);
collection.addCard(1, 'Goldnight Redeemer', SETS.BLESSEDVSCURSED);
collection.addCard(3, 'Golem Foundry', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Golgari Rot Farm', SETS.IZZETVSGOLGARI);
collection.addCard(1, 'Gore Vassal', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Gorehorn Minotaurs', SETS.CORE2012);

collection.addCard(1, 'Graaz, Unstoppable Juggernaut', SETS.ALLWILLBEONE);
collection.addCard(1, 'Graf Harvest', SETS.ELDRITCHMOON);
collection.addCard(1, 'Grafdigger\'s Cage', SETS.DARKASCENSION);
collection.addCard(2, 'Grafted Exoskeleton', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Granitic Titan', SETS.HOUROFDEVISTATION);
collection.addCard(3, 'Grasp of Darkness', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Grasp of Phantoms', SETS.INNISTRAD);
collection.addCard(2, 'Grave Bramble', SETS.INNISTRAD);
collection.addCard(4, 'Grave Exchange', SETS.AVACYNRESTORED);
collection.addCard(2, 'Gravebane Zombie', SETS.MIRAGE);
collection.addCard(1, 'Gravecrawler', SETS.BLESSEDVSCURSED);
collection.addCard(1, 'Gravedigger', SETS.CORE2015);
collection.addCard(4, 'Gravepurge', SETS.DARKASCENSION);
collection.addCard(4, 'Gravetiller Wurm', SETS.DARKASCENSION);
collection.addCard(1, 'Gray Merchant of Asphodel', SETS.THEROS);
collection.addCard(2, 'Grazing Kelpie', SETS.EVENTIDE);
collection.addCard(1, 'Greater Stone Spirit', SETS.COLDSNAP);
collection.addCard(3, 'Greatsword', SETS.CORE2012);
collection.addCard(1, 'Gremlin Mine', SETS.NEWPHYREXIA);
collection.addCard(3, 'Griffin Protector', SETS.CORE2013);
collection.addCard(5, 'Griffin Rider', SETS.CORE2012);
collection.addCard(1, 'Griffin Sentinel', SETS.CORE2010);
collection.addCard(3, 'Griffin Sentinel', SETS.CORE2012);
collection.addCard(1, 'Grim Affliction', SETS.NEWPHYREXIA);
collection.addCard(2, 'Grim Backwoods', SETS.DARKASCENSION);
collection.addCard(1, 'Grim Draugr', SETS.KALDHEIM, true);
collection.addCard(3, 'Grim Flowering', SETS.DARKASCENSION);
collection.addCard(1, 'Grim Lavamancer', SETS.CORE2012);
collection.addCard(1, 'Grim Physician', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Grimgrin, Corpse-Born', SETS.INNISTRAD);
collection.addCard(1, 'Griptide', SETS.DARKASCENSION);
collection.addCard(1, 'Grizzled Outrider', SETS.KALDHEIM);
collection.addCard(1, 'Grotag Siege-Runner', SETS.RISEOFTHEELDRAZI);
collection.addCard(1, 'Grotag Thrasher', SETS.WORLDWAKE);
collection.addCard(4, 'Grotesque Mutation', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Grounded', SETS.AVACYNRESTORED);
collection.addCard(2, 'Groundling Pouncer', SETS.EVENTIDE);
collection.addCard(4, 'Gruesome Deformity', SETS.INNISTRAD);
collection.addCard(5, 'Gruesome Discovery', SETS.DARKASCENSION);
collection.addCard(2, 'Gwyllion Hedge-Mage', SETS.EVENTIDE);
collection.addCard(1, 'Gryff\'s Boon', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Gryff Vanguard', SETS.BLESSEDVSCURSED);

collection.addCard(1, 'Guardian Lions', SETS.CORE2013);
collection.addCard(4, 'Guardians\' Pledge', SETS.CORE2012);
collection.addCard(3, 'Guardians of Akrasa', SETS.CORE2013);
collection.addCard(2, 'Guise of Fire', SETS.AVACYNRESTORED);
collection.addCard(2, 'Gurmag Swiftwing', SETS.KHANSOFTARKIR);
collection.addCard(1, 'Gut Shot', SETS.NEWPHYREXIA);
collection.addCard(1, 'Gutter Grime', SETS.INNISTRAD);
