
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(2, 'Haazda Snare Squad', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Hag Hedge-Mage', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Hagi Mob', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Halimar Wavewatch', SETS.RISEOFTHEELDRAZI);
COLLECTION.addCard(1, 'Hall of Tagsin', SETS.BROTHERSWAR);
COLLECTION.addCard(4, 'Halt Order', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Hand of Emrakul', SETS.RISEOFTHEELDRAZI);
COLLECTION.addCard(4, 'Hanweir Lancer', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Hanweir Militia Captain', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Harbor Bandit', SETS.CORE2013);
COLLECTION.addCard(1, 'Harm\'s Way', SETS.CORE2010);
COLLECTION.addCard(3, 'Harrowing Journey', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Harbor Serpent', SETS.CORE2012);
COLLECTION.addCard(2, 'Harbor Serpent', SETS.CORE2013);
COLLECTION.addCard(3, 'Harvest Gwyllion', SETS.EVENTIDE);
COLLECTION.addCard(5, 'Harvest Pyre', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Haunted Fengraf', SETS.DARKASCENSION);
COLLECTION.addCard(3, 'Haunted Guardian', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Havengul Skaab', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Hazardous Blast', SETS.ALLWILLBEONE);

COLLECTION.addCard(1, 'Healing Salve', SETS.EIGHTH);
COLLECTION.addCard(2, 'Heartlash Cinder', SETS.EVENTIDE);
COLLECTION.addCard(2, 'Heartstabber Mosquito', SETS.ZENDIKARVSELDRAZI);
COLLECTION.addCard(2, 'Heavy Arbalest', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(5, 'Heavy Mattock', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Heavyweight Demolisher', SETS.BROTHERSWAR);
COLLECTION.addCard(2, 'Heckling Fiends', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Hedron Blade', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(2, 'Hedron Crawler', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(4, 'Heirs of Stromkirk', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Heliod\'s Emissary', SETS.THEROS);
COLLECTION.addCard(1, 'Heliod\'s Pilgrim', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Hellion Eruption', SETS.ZENDIKARVSELDRAZI);
COLLECTION.addCard(1, 'Hellspark Elemental', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(1, 'Helvault', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Hexgold Halberd', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Hexgold Hoverwings', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Hexgold Slash', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Hexplate Golem', SETS.MIRRODINBESIEGED);

COLLECTION.addCard(4, 'Hideous Visage', SETS.CORE2012);
COLLECTION.addCard(1, 'Highland Lake', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(3, 'Hill Giant', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(1, 'Hill Giant', SETS.TENTH);
COLLECTION.addCard(3, 'Hindering Touch', SETS.SCOURGE);
COLLECTION.addCard(1, 'Hindervines', SETS.GATECRASH);
COLLECTION.addCard(1, 'Hinterland Harbor', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Hired Torturer', SETS.DRAGONSMAZE);
COLLECTION.addCard(2, 'Hive Stirrings', SETS.CORE2014);

COLLECTION.addCard(4, 'Hobgoblin Dragoon', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Hollowhead Sliver', SETS.MODERNHORIZONS);
COLLECTION.addCard(2, 'Hollowhenge Beast', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Hollowhenge Scavenger', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Holy Justiciar', SETS.AVACYNRESTORED);
COLLECTION.addCard(3, 'Homicidal Seclusion', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Hooded Assassin', SETS.FATEREFORGED);
COLLECTION.addCard(6, 'Hoof Skulkin', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Horizon Seeker', SETS.KALDHEIM);
COLLECTION.addCard(4, 'Horizon Spellbomb', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Horned Turtle', SETS.EIGHTH);
COLLECTION.addCard(1, 'Hornet Sting', SETS.CORE2011);
COLLECTION.addCard(1, 'Hostile Negotiations', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Hostile Realm', SETS.MORNINGTIDE);
COLLECTION.addCard(1, 'Hot Soup', SETS.CORE2015);
COLLECTION.addCard(4, 'Hotheaded Giant', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Hound of the Farbogs', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Hovermyr', SETS.NEWPHYREXIA);
COLLECTION.addCard(2, 'Howl of the Night Pack', SETS.CORE2014);
COLLECTION.addCard(1, 'Howlgeist', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Howling Mine', SETS.CORE2010);
COLLECTION.addCard(1, 'Howling Mine', SETS.BROTHERSWARRETROARTIFACTS, true);
COLLECTION.addCard(1, 'Howlpack Resurgence', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Howlpack Wolf', SETS.SHADOWSOVERINNISTRAD);

COLLECTION.addCard(2, 'Huatli, the Sun\'s Heart', SETS.WAROFTHESPARK);
COLLECTION.addCard(1, 'Hulking Devil', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Hulking Metamorph', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Human', 't'+SETS.AVACYNRESTORED, false, 2);
COLLECTION.addCard(5, 'Human', SETS.BLESSEDVSCURSED, false, 78);
COLLECTION.addCard(1, 'Humble', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Humble the Brute', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Hunger of the Howlpack', SETS.DARKASCENSION);
COLLECTION.addCard(2, 'Hunt the Weak', SETS.CORE2014);
COLLECTION.addCard(1, 'Hunted Ghoul', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Hunters\' Feast', SETS.CORE2011);
COLLECTION.addCard(1, 'Hunter\'s Insight', SETS.CORE2012);
COLLECTION.addCard(2, 'Hurly-Burly', SETS.LORWYN);

COLLECTION.addCard(1, 'Hydroform', SETS.GATECRASH);
COLLECTION.addCard(1, 'Hydrosurge', SETS.CORE2013);
COLLECTION.addCard(2, 'Hyrax Tower Scout', SETS.THEROSBEYONDDEATH);
