
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(2, 'Haazda Snare Squad', SETS.DRAGONSMAZE);
collection.addCard(1, 'Hag Hedge-Mage', SETS.EVENTIDE);
collection.addCard(1, 'Hagi Mob', SETS.KALDHEIM);
collection.addCard(1, 'Halimar Wavewatch', SETS.RISEOFTHEELDRAZI);
collection.addCard(1, 'Hall of Tagsin', SETS.BROTHERSWAR);
collection.addCard(4, 'Halt Order', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Hand of Emrakul', SETS.RISEOFTHEELDRAZI);
collection.addCard(4, 'Hanweir Lancer', SETS.AVACYNRESTORED);
collection.addCard(1, 'Hanweir Militia Captain', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Harbor Bandit', SETS.CORE2013);
collection.addCard(1, 'Harm\'s Way', SETS.CORE2010);
collection.addCard(3, 'Harrowing Journey', SETS.DARKASCENSION);
collection.addCard(1, 'Harbor Serpent', SETS.CORE2012);
collection.addCard(2, 'Harbor Serpent', SETS.CORE2013);
collection.addCard(3, 'Harvest Gwyllion', SETS.EVENTIDE);
collection.addCard(5, 'Harvest Pyre', SETS.INNISTRAD);
collection.addCard(2, 'Haunted Fengraf', SETS.DARKASCENSION);
collection.addCard(3, 'Haunted Guardian', SETS.AVACYNRESTORED);
collection.addCard(1, 'Havengul Skaab', SETS.AVACYNRESTORED);
collection.addCard(1, 'Hazardous Blast', SETS.ALLWILLBEONE);

collection.addCard(1, 'Healing Salve', SETS.EIGHTH);
collection.addCard(2, 'Heartlash Cinder', SETS.EVENTIDE);
collection.addCard(2, 'Heartstabber Mosquito', SETS.ZENDIKARVSELDRAZI);
collection.addCard(2, 'Heavy Arbalest', SETS.SCARSOFMIRRODIN);
collection.addCard(5, 'Heavy Mattock', SETS.DARKASCENSION);
collection.addCard(1, 'Heavyweight Demolisher', SETS.BROTHERSWAR);
collection.addCard(2, 'Heckling Fiends', SETS.DARKASCENSION);
collection.addCard(1, 'Hedron Blade', SETS.BATTLEFORZENDIKAR);
collection.addCard(2, 'Hedron Crawler', SETS.OATHOFTHEGATEWATCH);
collection.addCard(4, 'Heirs of Stromkirk', SETS.AVACYNRESTORED);
collection.addCard(1, 'Heliod\'s Emissary', SETS.THEROS);
collection.addCard(1, 'Heliod\'s Pilgrim', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Hellion Eruption', SETS.ZENDIKARVSELDRAZI);
collection.addCard(1, 'Hellspark Elemental', SETS.SORINVSINNISTRAD);
collection.addCard(1, 'Helvault', SETS.DARKASCENSION);
collection.addCard(1, 'Hexgold Halberd', SETS.ALLWILLBEONE);
collection.addCard(1, 'Hexgold Hoverwings', SETS.ALLWILLBEONE);
collection.addCard(1, 'Hexgold Slash', SETS.ALLWILLBEONE);
collection.addCard(1, 'Hexplate Golem', SETS.MIRRODINBESIEGED);

collection.addCard(4, 'Hideous Visage', SETS.CORE2012);
collection.addCard(1, 'Highland Lake', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Hill Giant', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Hill Giant', SETS.TENTH);
collection.addCard(3, 'Hindering Touch', SETS.SCOURGE);
collection.addCard(1, 'Hindervines', SETS.GATECRASH);
collection.addCard(1, 'Hinterland Harbor', SETS.INNISTRAD);
collection.addCard(1, 'Hired Torturer', SETS.DRAGONSMAZE);
collection.addCard(2, 'Hive Stirrings', SETS.CORE2014);

collection.addCard(4, 'Hobgoblin Dragoon', SETS.EVENTIDE);
collection.addCard(1, 'Hollowhead Sliver', SETS.MODERNHORIZONS);
collection.addCard(2, 'Hollowhenge Beast', SETS.DARKASCENSION);
collection.addCard(1, 'Hollowhenge Scavenger', SETS.INNISTRAD);
collection.addCard(1, 'Holy Justiciar', SETS.AVACYNRESTORED);
collection.addCard(3, 'Homicidal Seclusion', SETS.AVACYNRESTORED);
collection.addCard(1, 'Hooded Assassin', SETS.FATEREFORGED);
collection.addCard(6, 'Hoof Skulkin', SETS.EVENTIDE);
collection.addCard(1, 'Horizon Seeker', SETS.KALDHEIM);
collection.addCard(4, 'Horizon Spellbomb', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Horned Turtle', SETS.EIGHTH);
collection.addCard(1, 'Hornet Sting', SETS.CORE2011);
collection.addCard(1, 'Hostile Negotiations', SETS.BROTHERSWAR);
collection.addCard(1, 'Hostile Realm', SETS.MORNINGTIDE);
collection.addCard(1, 'Hot Soup', SETS.CORE2015);
collection.addCard(4, 'Hotheaded Giant', SETS.EVENTIDE);
collection.addCard(1, 'Hound of the Farbogs', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Hovermyr', SETS.NEWPHYREXIA);
collection.addCard(2, 'Howl of the Night Pack', SETS.CORE2014);
collection.addCard(1, 'Howlgeist', SETS.AVACYNRESTORED);
collection.addCard(1, 'Howling Mine', SETS.CORE2010);
collection.addCard(1, 'Howling Mine', SETS.BROTHERSWARRETROARTIFACTS, true);
collection.addCard(1, 'Howlpack Resurgence', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Howlpack Wolf', SETS.SHADOWSOVERINNISTRAD);

collection.addCard(2, 'Huatli, the Sun\'s Heart', SETS.WAROFTHESPARK);
collection.addCard(1, 'Hulking Devil', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Hulking Metamorph', SETS.BROTHERSWAR);
collection.addCard(1, 'Human', 't'+SETS.AVACYNRESTORED, false, 2);
collection.addCard(5, 'Human', SETS.BLESSEDVSCURSED, false, 78);
collection.addCard(1, 'Humble', SETS.ETERNALMASTERS);
collection.addCard(1, 'Humble the Brute', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Hunger of the Howlpack', SETS.DARKASCENSION);
collection.addCard(2, 'Hunt the Weak', SETS.CORE2014);
collection.addCard(1, 'Hunted Ghoul', SETS.AVACYNRESTORED);
collection.addCard(1, 'Hunters\' Feast', SETS.CORE2011);
collection.addCard(1, 'Hunter\'s Insight', SETS.CORE2012);
collection.addCard(2, 'Hurly-Burly', SETS.LORWYN);

collection.addCard(1, 'Hydroform', SETS.GATECRASH);
collection.addCard(1, 'Hydrosurge', SETS.CORE2013);
collection.addCard(2, 'Hyrax Tower Scout', SETS.THEROSBEYONDDEATH);
