
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(2, 'Ice Cage', SETS.CORE2011);
collection.addCard(3, 'Ice Cage', SETS.CORE2012);
collection.addCard(1, 'Iceberg Cancrix', SETS.MODERNHORIZONS);
collection.addCard(1, 'Icebind Pillar', SETS.KALDHEIM);
collection.addCard(2, 'Icefall', SETS.COLDSNAP);
collection.addCard(1, 'Icehide Troll', SETS.KALDHEIM);
collection.addCard(1, 'Ichor Rats', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Ichor Synthesizer', SETS.ALLWILLBEONE);
collection.addCard(3, 'Ichor Wellspring', SETS.MIRRODINBESIEGED);
collection.addCard(2, 'Ichorclaw Myr', SETS.SCARSOFMIRRODIN);
collection.addCard(2, 'Ichormoon Gauntlet', SETS.ALLWILLBEONE);

collection.addCard(3, 'Ideas Unbound', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Idol of Endurance', SETS.CORE2021, false, 342);

collection.addCard(1, 'Ignite Disorder', SETS.CORE2010);

collection.addCard(1, 'Illness in the Ranks', SETS.GATECRASH);
collection.addCard(1, 'Illusionary Servant', SETS.CORE2010);

collection.addCard(1, 'Imagecrafter', SETS.ONSLAUGHT);
collection.addCard(2, 'Immerwolf', SETS.DARKASCENSION);
collection.addCard(1, 'Impelled Giant', SETS.EVENTIDE);
collection.addCard(1, 'Implement of Examination', SETS.AETHERREVOLT);
collection.addCard(1, 'Implement of Ferocity', SETS.AETHERREVOLT);
collection.addCard(1, 'Impostor of the Sixth Pride', SETS.MODERNHORIZONS);

collection.addCard(1, 'Incendiary Oracle', SETS.THEROSBEYONDDEATH);
collection.addCard(4, 'Incinerate', SETS.CORE2012);
collection.addCard(2, 'Incite', SETS.CORE2011);
collection.addCard(1, 'Incorrigible Youths', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Increasing Confusion', SETS.DARKASCENSION);
collection.addCard(2, 'Increasing Devotion', SETS.DARKASCENSION);
collection.addCard(2, 'Increasing Vengeance', SETS.DARKASCENSION);
collection.addCard(1, 'Incubation Sac', SETS.ALLWILLBEONE);
collection.addCard(3, 'Incurable Ogre', SETS.SHARDSOFALARA);
collection.addCard(1, 'Index', SETS.CORE2013);
collection.addCard(1, 'Index', SETS.EIGHTH);
collection.addCard(1, 'Indigo Faerie', SETS.EVENTIDE);
collection.addCard(1, 'Induce Despair', SETS.ZENDIKARVSELDRAZI);
collection.addCard(2, 'Inescapable Brute', SETS.SHADOWMOOR);
collection.addCard(1, 'Infantry Veteran', SETS.CORE2011);
collection.addCard(1, 'Infectious Bite', SETS.ALLWILLBEONE);
collection.addCard(1, 'Infectious Bloodlust', SETS.MAGICORIGINS);
collection.addCard(1, 'Infernal Plunge', SETS.INNISTRAD);
collection.addCard(1, 'Inferno Jet', SETS.HOUROFDEVISTATION);
collection.addCard(1, 'Infested Fleshcutter', SETS.ALLWILLBEONE);
collection.addCard(2, 'Infiltration Lens', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Infiltrator\'s Magemark', SETS.GUILDPACT);
collection.addCard(5, 'Inflame', SETS.DARKSTEEL);
collection.addCard(1, 'Infuriate', SETS.THEROSBEYONDDEATH);
collection.addCard(2, 'Ingot Chewer', SETS.LORWYN);
collection.addCard(2, 'Inkfathom Divers', SETS.LORWYN);
collection.addCard(1, 'Inkfathom Witch', SETS.SHADOWMOOR);
collection.addCard(1, 'Inkmoth Nexus', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Inner Calm, Outer Strength', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Inner Struggle', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(5, 'Inner-Flame Acolyte', SETS.LORWYN);
collection.addCard(2, 'Inquisitor\'s Flail', SETS.INNISTRAD);
collection.addCard(2, 'Inside Out', SETS.EVENTIDE);
collection.addCard(1, 'Insidious Bookworms', SETS.ALLIANCES);
collection.addCard(4, 'Insolent Neonate', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Inspiration', SETS.EIGHTH);
collection.addCard(1, 'Inspire Awe', SETS.THEROSBEYONDDEATH);
collection.addCard(2, 'Inspired Charge', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Inspired Charge', SETS.CORE2011);
collection.addCard(2, 'Inspiring Captain', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Instill Infection', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Intangible Virtue', SETS.INNISTRAD);
collection.addCard(1, 'Intimidator Initiate', SETS.SHADOWMOOR);
collection.addCard(1, 'Into the Core', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Into the Fray', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Into the Maw of Hell', SETS.INNISTRAD);
collection.addCard(3, 'Intrepid Provisioner', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(2, 'Inquisitor\'s Ox', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Invasive Surgery', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Invoke the Divine', SETS.KALDHEIM);

collection.addCard(1, 'Iroas\'s Blessing', SETS.THEROSBEYONDDEATH);
collection.addCard(6, 'Iron Myr', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Iron-Craw Crusher', SETS.BROTHERSWAR);
collection.addCard(1, 'Irregular Cohort', SETS.MODERNHORIZONS);
collection.addCard(1, 'Irreverent Revelers', SETS.THEROSBEYONDDEATH);

collection.addCard(5, 'Island', SETS.THEROS, false, 234);
collection.addCard(5, 'Island', SETS.THEROS, false, 235);
collection.addCard(10, 'Island', SETS.THEROS, false, 236);
collection.addCard(5, 'Island', SETS.THEROS, false, 237);
collection.addCard(7, 'Island', SETS.CORE2014, false, 234);
collection.addCard(5, 'Island', SETS.CORE2014, false, 235);
collection.addCard(7, 'Island', SETS.CORE2014, false, 236);
collection.addCard(3, 'Island', SETS.CORE2014, false, 237);
collection.addCard(3, 'Island', SETS.BLESSEDVSCURSED, false, 35);
collection.addCard(2, 'Island', SETS.BLESSEDVSCURSED, false, 35);
collection.addCard(2, 'Island', SETS.BLESSEDVSCURSED, false, 35);
collection.addCard(3, 'Island', SETS.BLESSEDVSCURSED, false, 71);
collection.addCard(3, 'Island', SETS.BLESSEDVSCURSED, false, 72);
collection.addCard(2, 'Island', SETS.BLESSEDVSCURSED, false, 73);
collection.addCard(3, 'Island', SETS.INNISTRAD, false, 253);
collection.addCard(2, 'Island', SETS.INNISTRAD, false, 254);
collection.addCard(3, 'Island', SETS.INNISTRAD, false, 255);
collection.addCard(3, 'Island', SETS.CORE2013, false, 234);
collection.addCard(1, 'Island', SETS.CORE2013, true, 235);
collection.addCard(5, 'Island', SETS.CORE2013, false, 236);
collection.addCard(2, 'Island', SETS.CORE2013, false, 237);
collection.addCard(1, 'Island', SETS.RETURNTORAVNICA, false, 255);
collection.addCard(1, 'Island', SETS.RETURNTORAVNICA, false, 256);
collection.addCard(2, 'Island', SETS.RETURNTORAVNICA, false, 257);
collection.addCard(2, 'Island', SETS.RETURNTORAVNICA, false, 258);
collection.addCard(3, 'Island', SETS.TIMESPIRAL, false, 286);
collection.addCard(3, 'Island', SETS.TIMESPIRAL, false, 287);
collection.addCard(4, 'Island', SETS.TIMESPIRAL, false, 289);
collection.addCard(1, 'Island', SETS.ALLWILLBEONE, false, 263);
collection.addCard(2, 'Island', SETS.ALLWILLBEONE, false, 268);
collection.addCard(1, 'Island', SETS.MIRRODINBESIEGED, false, 148);
collection.addCard(1, 'Island', SETS.NEWPHYREXIA, false, 169);
collection.addCard(1, 'Island', SETS.SCARSOFMIRRODIN, false, 236);
collection.addCard(1, 'Island', SETS.AVACYNRESTORED, false, 235);
collection.addCard(1, 'Island', SETS.VENSERVSKOTH, false, 42);
collection.addCard(1, 'Island', SETS.CORE2011, false, 237);
collection.addCard(1, 'Island', SETS.BATTLEFORZENDIKAR, false, 257);
collection.addCard(1, 'Island', SETS.CORE2012, false, 235);
collection.addCard(1, 'Island', SETS.CORE2012, false, 237);
collection.addCard(10, 'Island', SETS.SHADOWSOVERINNISTRAD, false, 286);
collection.addCard(8, 'Island', SETS.SHADOWSOVERINNISTRAD, false, 287);
collection.addCard(11, 'Island', SETS.SHADOWSOVERINNISTRAD, false, 288);

collection.addCard(1, 'Ivory Giant', SETS.TIMESPIRALREMASTERED);

collection.addCard(1, 'Ixidor\'s Will', SETS.ONSLAUGHT);

collection.addCard(1, 'Izzet Guildgate', SETS.DRAGONSMAZE);
