
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(1, 'Macabre Waltz', SETS.MAGICORIGINS);
collection.addCard(1, 'Macabre Waltz', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Mad Prophet', SETS.AVACYNRESTORED);
collection.addCard(1, 'Mad Prophet', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Mad Prophet', SETS.SORINVSINNISTRAD);
collection.addCard(6, 'Magma Spray', SETS.SHARDSOFALARA);
collection.addCard(2, 'Magmatic Chasm', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Magmatic Sprinter', SETS.ALLWILLBEONE);
collection.addCard(1, 'Magmatic Sprinter', SETS.ALLWILLBEONE, true);
collection.addCard(3, 'Make a Wish', SETS.INNISTRAD);
collection.addCard(1, 'Makeshift Mauler', SETS.BLESSEDVSCURSED);
collection.addCard(4, 'Makeshift Mauler', SETS.INNISTRAD);
collection.addCard(1, 'Makeshift Munitions', SETS.COMMANDERLEGENDS);
collection.addCard(1, 'Makindi Sliderunner', SETS.BATTLEFORZENDIKAR);
collection.addCard(2, 'Malicious Intent', SETS.AVACYNRESTORED);
collection.addCard(1, 'Malignant Growth', SETS.MIRAGE);
collection.addCard(1, 'Mana Leak', SETS.CORE2011);
collection.addCard(1, 'Mana Seism', SETS.CHAMPIONSOFKAMIGAWA);
collection.addCard(1, 'Manabarbs', SETS.CORE2012);
collection.addCard(1, 'Manalith', SETS.CORE2012);
collection.addCard(1, 'Manalith', SETS.CORE2012, true);
collection.addCard(1, 'Manaweft Sliver', SETS.CORE2014);
collection.addCard(1, 'Manic Vandal', SETS.CORE2012);
collection.addCard(2, 'Manor Skeleton', SETS.INNISTRAD);
collection.addCard(1, 'Manriki-Gusari', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Manticore of the Gauntlet', SETS.AMONKHET);
collection.addCard(2, 'March of the Returned', SETS.THEROS);
collection.addCard(3, 'Mardu Skullhunter', SETS.KHANSOFTARKIR);
collection.addCard(1, 'Mardu Warshrieker', SETS.KHANSOFTARKIR);
collection.addCard(5, 'Mark of the Vampire', SETS.CORE2013);
collection.addCard(1, 'Marked by Honor', SETS.WELCOME2016);
collection.addCard(3, 'Markov Patrician', SETS.INNISTRAD);
collection.addCard(1, 'Marrow Bats', SETS.AVACYNRESTORED);
collection.addCard(1, 'Marrow Shards', SETS.NEWPHYREXIA);
collection.addCard(1, 'Marsh Casualties', SETS.ZENDIKARVSELDRAZI);
collection.addCard(2, 'Martyr of Ashes', SETS.COLDSNAP);
collection.addCard(1, 'Martyr of Bones', SETS.COLDSNAP);
collection.addCard(2, 'Martyr of Frost', SETS.COLDSNAP);
collection.addCard(1, 'Martyr of Spores', SETS.COLDSNAP);
collection.addCard(2, 'Mask of Avacyn', SETS.INNISTRAD);
collection.addCard(1, 'Mask of Avacyn', SETS.INNISTRAD, true);
collection.addCard(3, 'Mass Appeal', SETS.AVACYNRESTORED);
collection.addCard(1, 'Mass Appeal', SETS.AVACYNRESTORED, true);
collection.addCard(3, 'Master\'s Call', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Master Decoy', SETS.EIGHTH);
collection.addCard(1, 'Master of Diversion', SETS.CORE2014);
collection.addCard(1, 'Master Splicer', SETS.NEWPHYREXIA);
collection.addCard(1, 'Master Thief', SETS.CORE2012);
collection.addCard(2, 'Matsu-Tribe Birdstalker', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Maulfist Doorbuster', SETS.KALADESH);
collection.addCard(1, 'Mausoleum Guard', SETS.INNISTRAD);
collection.addCard(2, 'Maw of Kozilek', SETS.OATHOFTHEGATEWATCH);
collection.addCard(1, 'Maw of the Mire', SETS.INNISTRAD, true);
collection.addCard(1, 'Maze Behemoth', SETS.DRAGONSMAZE);
collection.addCard(1, 'Maze Glider', SETS.DRAGONSMAZE);
collection.addCard(2, 'Maze Sentinel', SETS.DRAGONSMAZE);
collection.addCard(1, 'Maze Skullbomb', SETS.ALLWILLBEONE);
collection.addCard(1, 'Maze\'s Mantle', SETS.ALLWILLBEONE);
collection.addCard(1, 'Maze\'s Mantle', SETS.ALLWILLBEONE, true);

collection.addCard(1, 'Megrim', SETS.CORE2010);
collection.addCard(1, 'Megrim', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Meldweb Strider', SETS.ALLWILLBEONE);
collection.addCard(1, 'Melira\'s Keepers', SETS.MIRRODINBESIEGED);
collection.addCard(6, 'Melt Terrain', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Memnite', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Memoricide', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Memory\'s Journey', SETS.INNISTRAD);
collection.addCard(3, 'Mental Agony', SETS.AVACYNRESTORED);
collection.addCard(1, 'Mental Vapors', SETS.GATECRASH);
collection.addCard(1, 'Mentor of the Meek', SETS.INNISTRAD);
collection.addCard(1, 'Mer-Ek Nightblade', SETS.KHANSOFTARKIR);
collection.addCard(2, 'Merchant of Secrets', SETS.EIGHTH);
collection.addCard(1, 'Merciless Resolve', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Mercurial Spelldancer', SETS.ALLWILLBEONE);
collection.addCard(1, 'Merfolk Looter', SETS.CORE2010);
collection.addCard(3, 'Merfolk Looter', SETS.CORE2012);
collection.addCard(3, 'Merfolk Mesmerist', SETS.CORE2012);
collection.addCard(1, 'Merfolk Seer', SETS.MIRAGE);
collection.addCard(1, 'Merfolk Spy', SETS.CORE2014);
collection.addCard(1, 'Merrow Bonegnawer', SETS.EVENTIDE);
collection.addCard(4, 'Merrow Levitator', SETS.EVENTIDE);
collection.addCard(1, 'Mesmerizing Dose', SETS.ALLWILLBEONE);
collection.addCard(2, 'Messenger Drake', SETS.CORE2014);
collection.addCard(1, 'Messenger\'s Speed', SETS.THEROS);

collection.addCard(4, 'Midnight Duelist', SETS.AVACYNRESTORED);
collection.addCard(5, 'Midnight Guard', SETS.DARKASCENSION);
collection.addCard(1, 'Midnight Haunting', SETS.INNISTRAD);
collection.addCard(4, 'Midvast Protector', SETS.AVACYNRESTORED);
collection.addCard(1, 'Might Beyond Reason', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Mighty Emergence', SETS.SHARDSOFALARA, true);
collection.addCard(4, 'Mighty Leap', SETS.CORE2012);
collection.addCard(1, 'Militant Inquisitor', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Mimic', SETS.ADVENTURESINTHEFORGOTTENREALMS, false, 349);
collection.addCard(3, 'Mimic Vat', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Mind Control', SETS.CORE2010);
collection.addCard(2, 'Mind Rot', SETS.CORE2012);
collection.addCard(3, 'Mind Rot', SETS.CORE2013);
collection.addCard(2, 'Mind Rot', SETS.CORE2014);
collection.addCard(2, 'Mind Rot', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Mind Rot', SETS.WELCOME2016);
collection.addCard(1, 'Mind Spring', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Mind Stone', SETS.ZENDIKARVSELDRAZI);
collection.addCard(1, 'Mind Swords', SETS.NEMESIS);
collection.addCard(1, 'Mindwrack Demon', SETS.BLESSEDVSCURSED, true);
collection.addCard(1, 'Minion\'s Return', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Minor Misstep', SETS.ALLWILLBEONE);
collection.addCard(1, 'Minotaur Abomination', SETS.CORE2014);
collection.addCard(1, 'Minotaur Skullcleaver', SETS.THEROS);
collection.addCard(1, 'Minsc, Beloved Ranger', SETS.ADVENTURESINTHEFORGOTTENREALMS);
collection.addCard(2, 'Mire\'s Grasp', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Mirko Vosk, Mind Drinker', SETS.DRAGONSMAZE);
collection.addCard(1, 'Mirrex', SETS.ALLWILLBEONE);
collection.addCard(1, 'Mirror Shield', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Mirror-Mad Phantasm', SETS.INNISTRAD);
collection.addCard(2, 'Mischievous Chimera', SETS.THEROSBEYONDDEATH);
collection.addCard(5, 'Misguided Rage', SETS.SCOURGE);
collection.addCard(1, 'Mishra\'s Bauble', SETS.BROTHERSWARRETROARTIFACTS);
collection.addCard(1, 'Mishra\'s Command', SETS.BROTHERSWAR);
collection.addCard(1, 'Mishra\'s Domination', SETS.BROTHERSWAR);
collection.addCard(1, 'Mishra\'s Research Desk', SETS.BROTHERSWAR);
collection.addCard(2, 'Mishra, Excavation Prodigy', SETS.BROTHERSWAR);
collection.addCard(1, 'Mist Intruder', SETS.BATTLEFORZENDIKAR);
collection.addCard(5, 'Mist Raven', SETS.AVACYNRESTORED);
collection.addCard(1, 'Mist Raven', SETS.BLESSEDVSCURSED);
collection.addCard(1, 'Mistform Wall', SETS.ONSLAUGHT);
collection.addCard(13, 'Mistform Warchief', SETS.SCOURGE);
collection.addCard(1, 'Mists of Littjara', SETS.KALDHEIM);

collection.addCard(1, 'Moan of the Unhallowed', SETS.BLESSEDVSCURSED);
collection.addCard(2, 'Moan of the Unhallowed', SETS.INNISTRAD);
collection.addCard(2, 'Mob', SETS.MODERNHORIZONS);
collection.addCard(1, 'Mogg Fanatic', SETS.FIREANDLIGHTNING, true);
collection.addCard(1, 'Mogg Salvage', SETS.NEMESIS);
collection.addCard(1, 'Mogg War Marshal', SETS.TIMESPIRAL);
collection.addCard(1, 'Mogg War Marshal', SETS.TIMESPIRALREMASTERED);
collection.addCard(1, 'Mogis\'s Favor', SETS.THEROSBEYONDDEATH);
collection.addCard(3, 'Molder Beast', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Moldgraf Monstrosity', SETS.INNISTRAD);
collection.addCard(1, 'Moldgraf Scavenger', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Molten Rain', SETS.MIRRODIN);
collection.addCard(1, 'Molten Rebuke', SETS.ALLWILLBEONE);
collection.addCard(1, 'Molting Snakeskin', SETS.KHANSOFTARKIR);
collection.addCard(2, 'Moment of Heroism', SETS.INNISTRAD);
collection.addCard(1, 'Momentary Blink', SETS.BLESSEDVSCURSED);
collection.addCard(3, 'Monstrify', SETS.EVENTIDE);
collection.addCard(5, 'Moon Heron', SETS.INNISTRAD);
collection.addCard(3, 'Moonlight Geist', SETS.AVACYNRESTORED);
collection.addCard(1, 'Moonsilver Spear', SETS.AVACYNRESTORED);
collection.addCard(1, 'Moonwing Moth', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Moorland Drifter', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Moorland Inquisitor', SETS.AVACYNRESTORED);
collection.addCard(1, 'Moorland Inquisitor', SETS.BLESSEDVSCURSED);
collection.addCard(2, 'Morbid Plunder', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Morgue Burst', SETS.DRAGONSMAZE);
collection.addCard(2, 'Moriok Reaver', SETS.SCARSOFMIRRODIN);
collection.addCard(2, 'Moriok Replica', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Morkrut Banshee', SETS.INNISTRAD);
collection.addCard(6, 'Mortarpod', SETS.MIRRODINBESIEGED);
collection.addCard(3, 'Moss Viper', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Mothdust Changeling', SETS.MORNINGTIDE);
collection.addCard(2, 'Mother Bear', SETS.MODERNHORIZONS);

collection.addCard(2, 'Mountain', SETS.ALLWILLBEONE, false, 270);
collection.addCard(1, 'Mountain', SETS.AVACYNRESTORED, false, 240);
collection.addCard(1, 'Mountain', SETS.AVACYNRESTORED, false, 241);
collection.addCard(1, 'Mountain', SETS.BATTLEFORZENDIKAR, false, 266);
collection.addCard(1, 'Mountain', SETS.BROTHERSWAR, false, 275);
collection.addCard(1, 'Mountain', SETS.CORE2012, false, 243);
collection.addCard(1, 'Mountain', SETS.CORE2012, false, 244);
collection.addCard(1, 'Mountain', SETS.CORE2013, false, 242);
collection.addCard(1, 'Mountain', SETS.CORE2013, false, 245);
collection.addCard(4, 'Mountain', SETS.CORE2014, false, 242);
collection.addCard(3, 'Mountain', SETS.CORE2014, false, 243);
collection.addCard(1, 'Mountain', SETS.CORE2014, false, 244);
collection.addCard(1, 'Mountain', SETS.CORE2014, false, 245);
collection.addCard(1, 'Mountain', SETS.CORE2015, false, 262);
collection.addCard(1, 'Mountain', SETS.FIREANDLIGHTNING, true, 31);
collection.addCard(1, 'Mountain', SETS.FIREANDLIGHTNING, true, 32);
collection.addCard(1, 'Mountain', SETS.INNISTRAD, false, 259);
collection.addCard(1, 'Mountain', SETS.INNISTRAD, false, 260);
collection.addCard(1, 'Mountain', SETS.KHANSOFTARKIR, false, 264);
collection.addCard(1, 'Mountain', SETS.RETURNTORAVNICA, false, 267);
collection.addCard(9, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 292);
collection.addCard(10, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 293);
collection.addCard(10, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 294);
collection.addCard(5, 'Mountain', SETS.SORINVSINNISTRAD, false, 75);
collection.addCard(5, 'Mountain', SETS.SORINVSINNISTRAD, false, 76);
collection.addCard(1, 'Mountain', SETS.SORINVSINNISTRAD, false, 77);
collection.addCard(1, 'Mountain', SETS.THEROS, false, 245);
collection.addCard(1, 'Mountain', SETS.VENSERVSKOTH, false, 74);
collection.addCard(3, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 73);
collection.addCard(2, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 74);
collection.addCard(2, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 75);

collection.addCard(2, 'Mudbrawler Cohort', SETS.SHADOWMOOR);
collection.addCard(1, 'Mudbutton Torchrunner', SETS.LORWYN);
collection.addCard(1, 'Mugging', SETS.GATECRASH);
collection.addCard(4, 'Mulch', SETS.INNISTRAD);
collection.addCard(1, 'Mulldrifter', SETS.LORWYN);
collection.addCard(3, 'Murder', SETS.CORE2013);
collection.addCard(1, 'Murder of Crows', SETS.INNISTRAD);
collection.addCard(1, 'Murderous Compulsion', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Mutagenic Growth', SETS.NEWPHYREXIA);
collection.addCard(1, 'Mutilate', SETS.CORE2013);

collection.addCard(1, 'Mwonvuli Beast Tracker', SETS.CORE2013);

collection.addCard(1, 'Mycosynth Wellspring', SETS.NEWPHYREXIA);
collection.addCard(1, 'Myr Battlesphere', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Myr Galvanizer', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Myr Reservoir', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Myrsmith', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Mystic of the Hidden Way', SETS.KHANSOFTARKIR);
collection.addCard(2, 'Mystic Retrieval', SETS.DARKASCENSION);
