
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(1, 'Macabre Waltz', SETS.MAGICORIGINS);
COLLECTION.addCard(1, 'Macabre Waltz', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(3, 'Mad Prophet', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Mad Prophet', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Mad Prophet', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(6, 'Magma Spray', SETS.SHARDSOFALARA);
COLLECTION.addCard(2, 'Magmatic Chasm', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Magmatic Sprinter', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Magmatic Sprinter', SETS.ALLWILLBEONE, true);
COLLECTION.addCard(3, 'Make a Wish', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Makeshift Mauler', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(4, 'Makeshift Mauler', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Makeshift Munitions', SETS.COMMANDERLEGENDS);
COLLECTION.addCard(1, 'Makindi Sliderunner', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(2, 'Malicious Intent', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Malignant Growth', SETS.MIRAGE);
COLLECTION.addCard(1, 'Mana Leak', SETS.CORE2011);
COLLECTION.addCard(1, 'Mana Seism', SETS.CHAMPIONSOFKAMIGAWA);
COLLECTION.addCard(1, 'Manabarbs', SETS.CORE2012);
COLLECTION.addCard(1, 'Manalith', SETS.CORE2012);
COLLECTION.addCard(1, 'Manalith', SETS.CORE2012, true);
COLLECTION.addCard(1, 'Manaweft Sliver', SETS.CORE2014);
COLLECTION.addCard(1, 'Manic Vandal', SETS.CORE2012);
COLLECTION.addCard(2, 'Manor Skeleton', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Manriki-Gusari', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Manticore of the Gauntlet', SETS.AMONKHET);
COLLECTION.addCard(2, 'March of the Returned', SETS.THEROS);
COLLECTION.addCard(3, 'Mardu Skullhunter', SETS.KHANSOFTARKIR);
COLLECTION.addCard(1, 'Mardu Warshrieker', SETS.KHANSOFTARKIR);
COLLECTION.addCard(5, 'Mark of the Vampire', SETS.CORE2013);
COLLECTION.addCard(1, 'Marked by Honor', SETS.WELCOME2016);
COLLECTION.addCard(3, 'Markov Patrician', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Marrow Bats', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Marrow Shards', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Marsh Casualties', SETS.ZENDIKARVSELDRAZI);
COLLECTION.addCard(2, 'Martyr of Ashes', SETS.COLDSNAP);
COLLECTION.addCard(1, 'Martyr of Bones', SETS.COLDSNAP);
COLLECTION.addCard(2, 'Martyr of Frost', SETS.COLDSNAP);
COLLECTION.addCard(1, 'Martyr of Spores', SETS.COLDSNAP);
COLLECTION.addCard(2, 'Mask of Avacyn', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Mask of Avacyn', SETS.INNISTRAD, true);
COLLECTION.addCard(3, 'Mass Appeal', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Mass Appeal', SETS.AVACYNRESTORED, true);
COLLECTION.addCard(3, 'Master\'s Call', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Master Decoy', SETS.EIGHTH);
COLLECTION.addCard(1, 'Master of Diversion', SETS.CORE2014);
COLLECTION.addCard(1, 'Master Splicer', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Master Thief', SETS.CORE2012);
COLLECTION.addCard(2, 'Matsu-Tribe Birdstalker', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Maulfist Doorbuster', SETS.KALADESH);
COLLECTION.addCard(1, 'Mausoleum Guard', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Maw of Kozilek', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(1, 'Maw of the Mire', SETS.INNISTRAD, true);
COLLECTION.addCard(1, 'Maze Behemoth', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Maze Glider', SETS.DRAGONSMAZE);
COLLECTION.addCard(2, 'Maze Sentinel', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Maze Skullbomb', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Maze\'s Mantle', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Maze\'s Mantle', SETS.ALLWILLBEONE, true);

COLLECTION.addCard(1, 'Megrim', SETS.CORE2010);
COLLECTION.addCard(1, 'Megrim', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(1, 'Meldweb Strider', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Melira\'s Keepers', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(6, 'Melt Terrain', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(3, 'Memnite', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Memoricide', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Memory\'s Journey', SETS.INNISTRAD);
COLLECTION.addCard(3, 'Mental Agony', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Mental Vapors', SETS.GATECRASH);
COLLECTION.addCard(1, 'Mentor of the Meek', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Mer-Ek Nightblade', SETS.KHANSOFTARKIR);
COLLECTION.addCard(2, 'Merchant of Secrets', SETS.EIGHTH);
COLLECTION.addCard(1, 'Merciless Resolve', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Mercurial Spelldancer', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Merfolk Looter', SETS.CORE2010);
COLLECTION.addCard(3, 'Merfolk Looter', SETS.CORE2012);
COLLECTION.addCard(3, 'Merfolk Mesmerist', SETS.CORE2012);
COLLECTION.addCard(1, 'Merfolk Seer', SETS.MIRAGE);
COLLECTION.addCard(1, 'Merfolk Spy', SETS.CORE2014);
COLLECTION.addCard(1, 'Merrow Bonegnawer', SETS.EVENTIDE);
COLLECTION.addCard(4, 'Merrow Levitator', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Mesmerizing Dose', SETS.ALLWILLBEONE);
COLLECTION.addCard(2, 'Messenger Drake', SETS.CORE2014);
COLLECTION.addCard(1, 'Messenger\'s Speed', SETS.THEROS);

COLLECTION.addCard(4, 'Midnight Duelist', SETS.AVACYNRESTORED);
COLLECTION.addCard(5, 'Midnight Guard', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Midnight Haunting', SETS.INNISTRAD);
COLLECTION.addCard(4, 'Midvast Protector', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Might Beyond Reason', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Mighty Emergence', SETS.SHARDSOFALARA, true);
COLLECTION.addCard(4, 'Mighty Leap', SETS.CORE2012);
COLLECTION.addCard(1, 'Militant Inquisitor', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Mimic', SETS.ADVENTURESINTHEFORGOTTENREALMS, false, 349);
COLLECTION.addCard(3, 'Mimic Vat', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Mind Control', SETS.CORE2010);
COLLECTION.addCard(2, 'Mind Rot', SETS.CORE2012);
COLLECTION.addCard(3, 'Mind Rot', SETS.CORE2013);
COLLECTION.addCard(2, 'Mind Rot', SETS.CORE2014);
COLLECTION.addCard(2, 'Mind Rot', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(1, 'Mind Rot', SETS.WELCOME2016);
COLLECTION.addCard(1, 'Mind Spring', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(1, 'Mind Stone', SETS.ZENDIKARVSELDRAZI);
COLLECTION.addCard(1, 'Mind Swords', SETS.NEMESIS);
COLLECTION.addCard(1, 'Mindwrack Demon', SETS.BLESSEDVSCURSED, true);
COLLECTION.addCard(1, 'Minion\'s Return', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Minor Misstep', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Minotaur Abomination', SETS.CORE2014);
COLLECTION.addCard(1, 'Minotaur Skullcleaver', SETS.THEROS);
COLLECTION.addCard(1, 'Minsc, Beloved Ranger', SETS.ADVENTURESINTHEFORGOTTENREALMS);
COLLECTION.addCard(2, 'Mire\'s Grasp', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Mirko Vosk, Mind Drinker', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Mirrex', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Mirror Shield', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Mirror-Mad Phantasm', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Mischievous Chimera', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(5, 'Misguided Rage', SETS.SCOURGE);
COLLECTION.addCard(1, 'Mishra\'s Bauble', SETS.BROTHERSWARRETROARTIFACTS);
COLLECTION.addCard(1, 'Mishra\'s Command', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Mishra\'s Domination', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Mishra\'s Research Desk', SETS.BROTHERSWAR);
COLLECTION.addCard(2, 'Mishra, Excavation Prodigy', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Mist Intruder', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(5, 'Mist Raven', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Mist Raven', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Mistform Wall', SETS.ONSLAUGHT);
COLLECTION.addCard(13, 'Mistform Warchief', SETS.SCOURGE);
COLLECTION.addCard(1, 'Mists of Littjara', SETS.KALDHEIM);

COLLECTION.addCard(1, 'Moan of the Unhallowed', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(2, 'Moan of the Unhallowed', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Mob', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Mogg Fanatic', SETS.FIREANDLIGHTNING, true);
COLLECTION.addCard(1, 'Mogg Salvage', SETS.NEMESIS);
COLLECTION.addCard(1, 'Mogg War Marshal', SETS.TIMESPIRAL);
COLLECTION.addCard(1, 'Mogg War Marshal', SETS.TIMESPIRALREMASTERED);
COLLECTION.addCard(1, 'Mogis\'s Favor', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(3, 'Molder Beast', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Moldgraf Monstrosity', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Moldgraf Scavenger', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Molten Rain', SETS.MIRRODIN);
COLLECTION.addCard(1, 'Molten Rebuke', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Molting Snakeskin', SETS.KHANSOFTARKIR);
COLLECTION.addCard(2, 'Moment of Heroism', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Momentary Blink', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(3, 'Monstrify', SETS.EVENTIDE);
COLLECTION.addCard(5, 'Moon Heron', SETS.INNISTRAD);
COLLECTION.addCard(3, 'Moonlight Geist', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Moonsilver Spear', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Moonwing Moth', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Moorland Drifter', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Moorland Inquisitor', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Moorland Inquisitor', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(2, 'Morbid Plunder', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Morgue Burst', SETS.DRAGONSMAZE);
COLLECTION.addCard(2, 'Moriok Reaver', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Moriok Replica', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Morkrut Banshee', SETS.INNISTRAD);
COLLECTION.addCard(6, 'Mortarpod', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(3, 'Moss Viper', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Mothdust Changeling', SETS.MORNINGTIDE);
COLLECTION.addCard(2, 'Mother Bear', SETS.MODERNHORIZONS);

COLLECTION.addCard(2, 'Mountain', SETS.ALLWILLBEONE, false, 270);
COLLECTION.addCard(1, 'Mountain', SETS.AVACYNRESTORED, false, 240);
COLLECTION.addCard(1, 'Mountain', SETS.AVACYNRESTORED, false, 241);
COLLECTION.addCard(1, 'Mountain', SETS.BATTLEFORZENDIKAR, false, 266);
COLLECTION.addCard(1, 'Mountain', SETS.BROTHERSWAR, false, 275);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2012, false, 243);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2012, false, 244);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2013, false, 242);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2013, false, 245);
COLLECTION.addCard(4, 'Mountain', SETS.CORE2014, false, 242);
COLLECTION.addCard(3, 'Mountain', SETS.CORE2014, false, 243);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2014, false, 244);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2014, false, 245);
COLLECTION.addCard(1, 'Mountain', SETS.CORE2015, false, 262);
COLLECTION.addCard(1, 'Mountain', SETS.FIREANDLIGHTNING, true, 31);
COLLECTION.addCard(1, 'Mountain', SETS.FIREANDLIGHTNING, true, 32);
COLLECTION.addCard(1, 'Mountain', SETS.INNISTRAD, false, 259);
COLLECTION.addCard(1, 'Mountain', SETS.INNISTRAD, false, 260);
COLLECTION.addCard(1, 'Mountain', SETS.KHANSOFTARKIR, false, 264);
COLLECTION.addCard(1, 'Mountain', SETS.RETURNTORAVNICA, false, 267);
COLLECTION.addCard(9, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 292);
COLLECTION.addCard(10, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 293);
COLLECTION.addCard(10, 'Mountain', SETS.SHADOWSOVERINNISTRAD, false, 294);
COLLECTION.addCard(5, 'Mountain', SETS.SORINVSINNISTRAD, false, 75);
COLLECTION.addCard(5, 'Mountain', SETS.SORINVSINNISTRAD, false, 76);
COLLECTION.addCard(1, 'Mountain', SETS.SORINVSINNISTRAD, false, 77);
COLLECTION.addCard(1, 'Mountain', SETS.THEROS, false, 245);
COLLECTION.addCard(1, 'Mountain', SETS.VENSERVSKOTH, false, 74);
COLLECTION.addCard(3, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 73);
COLLECTION.addCard(2, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 74);
COLLECTION.addCard(2, 'Mountain', SETS.ZENDIKARVSELDRAZI, false, 75);

COLLECTION.addCard(2, 'Mudbrawler Cohort', SETS.SHADOWMOOR);
COLLECTION.addCard(1, 'Mudbutton Torchrunner', SETS.LORWYN);
COLLECTION.addCard(1, 'Mugging', SETS.GATECRASH);
COLLECTION.addCard(4, 'Mulch', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Mulldrifter', SETS.LORWYN);
COLLECTION.addCard(3, 'Murder', SETS.CORE2013);
COLLECTION.addCard(1, 'Murder of Crows', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Murderous Compulsion', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Mutagenic Growth', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Mutilate', SETS.CORE2013);

COLLECTION.addCard(1, 'Mwonvuli Beast Tracker', SETS.CORE2013);

COLLECTION.addCard(1, 'Mycosynth Wellspring', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Myr Battlesphere', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Myr Galvanizer', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Myr Reservoir', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(3, 'Myrsmith', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Mystic of the Hidden Way', SETS.KHANSOFTARKIR);
COLLECTION.addCard(2, 'Mystic Retrieval', SETS.DARKASCENSION);
