
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(5, 'Pacifism', SETS.CORE2012);
COLLECTION.addCard(3, 'Pacifism', SETS.CORE2013);
COLLECTION.addCard(2, 'Pacifism', SETS.CORE2014);
COLLECTION.addCard(1, 'Pack Guardian', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Painsmith', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Palace Guard', SETS.CORE2010);
COLLECTION.addCard(1, 'Palace Guard', SETS.CORE2011);
COLLECTION.addCard(1, 'Palisade Giant', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Palladium Myr', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Panic Attack', SETS.CORE2010);
COLLECTION.addCard(1, 'Panic Spellbomb', SETS.SCARSOFMIRRODIN, true);
COLLECTION.addCard(1, 'Paralyzing Grasp', SETS.RETURNTORAVNICA);
COLLECTION.addCard(2, 'Paraselene', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Path of Anger\'s Flame', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Path to the World Tree', SETS.KALDHEIM);
COLLECTION.addCard(4, 'Pathbreaker Wurm', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Patrol Signaler', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Pawn of Ulamog', SETS.ZENDIKARVSELDRAZI);

COLLECTION.addCard(1, 'Penumbra Spider', SETS.TIMESPIRALREMASTERED);
COLLECTION.addCard(4, 'Peregrine Griffin', SETS.CORE2012);
COLLECTION.addCard(1, 'Perilous Shadow', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Perplexing Chimera', SETS.BORNOFTHEGODS);
COLLECTION.addCard(3, 'Pestermite', SETS.LORWYN);

COLLECTION.addCard(2, 'Phantasmal Bear', SETS.CORE2012);
COLLECTION.addCard(1, 'Phantasmal Form', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Phantom Monster', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Phantom Ninja', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Phantom Nomad', SETS.JUDGMENT);
COLLECTION.addCard(4, 'Phantom Warrior', SETS.CORE2010);
COLLECTION.addCard(1, 'Phantom Warrior', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(1, 'Pharika\'s Libation', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Pheres-Band Centaurs', SETS.THEROS);
COLLECTION.addCard(3, 'Phyresis', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Phyrexian Arena', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Phyrexian Beast', 't'+SETS.ALLWILLBEONE, false, 6);
COLLECTION.addCard(1, 'Phyrexian Driver', SETS.NEMESIS);
COLLECTION.addCard(1, 'Phyrexian Ingester', SETS.NEWPHYREXIA, true);
COLLECTION.addCard(3, 'Phyrexian Mite', 't'+SETS.ALLWILLBEONE, false, 11);
COLLECTION.addCard(1, 'Phyrexian Monitor', SETS.URZASDESTINY);
COLLECTION.addCard(1, 'Phyrexian Swarmlord', SETS.NEWPHYREXIA, true);

COLLECTION.addCard(1, 'Pieces of the Puzzle', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(2, 'Pilfering Hawk', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Pillage', SETS.MODERNHORIZONS);
COLLECTION.addCard(3, 'Pillar of Flame', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Pillar of Flame', SETS.AVACYNRESTORED, true);
COLLECTION.addCard(1, 'Pillarfield Ox', SETS.CORE2013);
COLLECTION.addCard(1, 'Pincher Beetles', SETS.TENTH);
COLLECTION.addCard(5, 'Pitchburn Devils', SETS.INNISTRAD);

COLLECTION.addCard(1, 'Plague Myr', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(4, 'Plague Stinger', SETS.SCARSOFMIRRODIN);

COLLECTION.addCard(1, 'Plains', SETS.ALLWILLBEONE, false, 262);
COLLECTION.addCard(1, 'Plains', SETS.ALLWILLBEONE, true, 262);
COLLECTION.addCard(1, 'Plains', SETS.ALLWILLBEONE, false, 267);
COLLECTION.addCard(1, 'Plains', SETS.BATTLEFORZENDIKAR, false, 252);
COLLECTION.addCard(4, 'Plains', SETS.BLESSEDVSCURSED, false, 38);
COLLECTION.addCard(5, 'Plains', SETS.BLESSEDVSCURSED, false, 39);
COLLECTION.addCard(4, 'Plains', SETS.BLESSEDVSCURSED, false, 40);
COLLECTION.addCard(1, 'Plains', SETS.CORE2012, false, 232);
COLLECTION.addCard(1, 'Plains', SETS.CORE2012, false, 233);
COLLECTION.addCard(3, 'Plains', SETS.CORE2013, false, 230);
COLLECTION.addCard(3, 'Plains', SETS.CORE2013, false, 231);
COLLECTION.addCard(6, 'Plains', SETS.CORE2013, false, 232);
COLLECTION.addCard(1, 'Plains', SETS.CORE2013, false, 233);
COLLECTION.addCard(4, 'Plains', SETS.CORE2014, false, 230);
COLLECTION.addCard(4, 'Plains', SETS.CORE2014, false, 231);
COLLECTION.addCard(6, 'Plains', SETS.CORE2014, false, 232);
COLLECTION.addCard(5, 'Plains', SETS.CORE2014, false, 233);
COLLECTION.addCard(1, 'Plains', SETS.CORE2015, false, 250);
COLLECTION.addCard(2, 'Plains', SETS.INNISTRAD, false, 250);
COLLECTION.addCard(4, 'Plains', SETS.INNISTRAD, false, 251);
COLLECTION.addCard(1, 'Plains', SETS.INNISTRAD, false, 252);
COLLECTION.addCard(2, 'Plains', SETS.MIRRODINBESIEGED, false, 146);
COLLECTION.addCard(3, 'Plains', SETS.MIRRODINBESIEGED, false, 147);
COLLECTION.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 250);
COLLECTION.addCard(3, 'Plains', SETS.RETURNTORAVNICA, false, 251);
COLLECTION.addCard(3, 'Plains', SETS.RETURNTORAVNICA, false, 252);
COLLECTION.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 253);
COLLECTION.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 254);
COLLECTION.addCard(5, 'Plains', SETS.THEROS, false, 230);
COLLECTION.addCard(7, 'Plains', SETS.THEROS, false, 231);
COLLECTION.addCard(4, 'Plains', SETS.THEROS, false, 232);
COLLECTION.addCard(6, 'Plains', SETS.THEROS, false, 233);
COLLECTION.addCard(11, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 283);
COLLECTION.addCard(10, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 284);
COLLECTION.addCard(8, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 285);
COLLECTION.addCard(3, 'Plains', SETS.SORINVSINNISTRAD, false, 39);
COLLECTION.addCard(2, 'Plains', SETS.SORINVSINNISTRAD, false, 40);
COLLECTION.addCard(1, 'Plains', SETS.THEROS, false, 230);
COLLECTION.addCard(1, 'Plains', SETS.ZENDIKAR, false, '231a');

COLLECTION.addCard(1, 'Planar Disruption', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Plated Seastrider', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Plated Wurm', SETS.PORTALSECONDAGE);
COLLECTION.addCard(1, 'Plow Through Reito', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(3, 'Plummet', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(3, 'Plummet', SETS.CORE2012);
COLLECTION.addCard(1, 'Plummet', SETS.CORE2013);
COLLECTION.addCard(1, 'Plunder', SETS.TIMESPIRAL);

COLLECTION.addCard(1, 'Poison Counter', 't'+SETS.ALLWILLBEONE, false, 14);
COLLECTION.addCard(1, 'Poison the Cup', SETS.KALDHEIM);
COLLECTION.addCard(3, 'Polluted Dead', SETS.AVACYNRESTORED);
COLLECTION.addCard(4, 'Ponder', SETS.CORE2012);
COLLECTION.addCard(1, 'Porcelain Zealot', SETS.ALLWILLBEONE);
COLLECTION.addCard(3, 'Pore Over the Pages', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Port of Karfell', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Power of Fire', SETS.SHADOWMOOR);
COLLECTION.addCard(1, 'Powerstone', 't'+SETS.BROTHERSWAR, false, 7);

COLLECTION.addCard(1, 'Predation Steward', SETS.ALLWILLBEONE);
COLLECTION.addCard(4, 'Predator\'s Gambit', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Prescient Chimera', SETS.THEROS);
COLLECTION.addCard(1, 'Presence of Gond', SETS.MASTERS25);
COLLECTION.addCard(2, 'Press into Service', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(3, 'Prey Upon', SETS.CORE2013);
COLLECTION.addCard(2, 'Prey Upon', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Price of Progress', SETS.FIREANDLIGHTNING);
COLLECTION.addCard(5, 'Pride Guardian', SETS.CORE2012);
COLLECTION.addCard(3, 'Priests of Norn', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(3, 'Primal Huntbeast', SETS.CORE2013);
COLLECTION.addCard(1, 'Primordial Hydra', SETS.CORE2012);
COLLECTION.addCard(1, 'Prismatic Strands', SETS.JUDGMENT);
COLLECTION.addCard(1, 'Prismwake Merrow', SETS.SHADOWMOOR);
COLLECTION.addCard(1, 'Pristine Talisman', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Prized Elephant', SETS.CORE2013);
COLLECTION.addCard(1, 'Promised Kannushi', SETS.SAVIORSOFKAMIGAWA);

COLLECTION.addCard(3, 'Psychic Miasma', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Psychotic Haze', SETS.TORMENT);
COLLECTION.addCard(1, 'Psychotic Fury', SETS.DISSENSION);

COLLECTION.addCard(4, 'Public Execution', SETS.CORE2013);
COLLECTION.addCard(4, 'Puncture Blast', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Puncturing Blow', SETS.HOUROFDEVISTATION);
COLLECTION.addCard(2, 'Puncturing Light', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Purify the Grave', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Pursue Glory', SETS.AMONKHET);
COLLECTION.addCard(1, 'Pursuit of Flight', SETS.RETURNTORAVNICA);
COLLECTION.addCard(2, 'Putrid Goblin', SETS.MODERNHORIZONS);

COLLECTION.addCard(1, 'Pyre Hound', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Pyreheart Wolf', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Pyretic Ritual', SETS.CORE2011);
COLLECTION.addCard(1, 'Pyroblast', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Pyroclasm', SETS.EIGHTH);
COLLECTION.addCard(1, 'Pyroclastic Elemental', SETS.JUMPSTART);
COLLECTION.addCard(2, 'Pyroconvergence', SETS.RETURNTORAVNICA);
COLLECTION.addCard(4, 'Pyrostatic Pillar', SETS.SCOURGE);
