
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(5, 'Pacifism', SETS.CORE2012);
collection.addCard(3, 'Pacifism', SETS.CORE2013);
collection.addCard(2, 'Pacifism', SETS.CORE2014);
collection.addCard(1, 'Pack Guardian', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Painsmith', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Palace Guard', SETS.CORE2010);
collection.addCard(1, 'Palace Guard', SETS.CORE2011);
collection.addCard(1, 'Palisade Giant', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Palladium Myr', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Panic Attack', SETS.CORE2010);
collection.addCard(2, 'Panic Spellbomb', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Panic Spellbomb', SETS.SCARSOFMIRRODIN, true);
collection.addCard(1, 'Paralyzing Grasp', SETS.RETURNTORAVNICA);
collection.addCard(2, 'Paraselene', SETS.INNISTRAD);
collection.addCard(1, 'Path of Anger\'s Flame', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Path to the World Tree', SETS.KALDHEIM);
collection.addCard(4, 'Pathbreaker Wurm', SETS.AVACYNRESTORED);
collection.addCard(1, 'Patrol Signaler', SETS.EVENTIDE);
collection.addCard(1, 'Pawn of Ulamog', SETS.ZENDIKARVSELDRAZI);

collection.addCard(2, 'Peace Strider', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Penumbra Spider', SETS.TIMESPIRALREMASTERED);
collection.addCard(4, 'Peregrine Griffin', SETS.CORE2012);
collection.addCard(7, 'Perilous Myr', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Perilous Shadow', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Perplexing Chimera', SETS.BORNOFTHEGODS);
collection.addCard(3, 'Pestermite', SETS.LORWYN);

collection.addCard(2, 'Phantasmal Bear', SETS.CORE2012);
collection.addCard(1, 'Phantasmal Form', SETS.MODERNHORIZONS);
collection.addCard(1, 'Phantom Monster', SETS.ETERNALMASTERS);
collection.addCard(1, 'Phantom Ninja', SETS.MODERNHORIZONS);
collection.addCard(1, 'Phantom Nomad', SETS.JUDGMENT);
collection.addCard(4, 'Phantom Warrior', SETS.CORE2010);
collection.addCard(1, 'Phantom Warrior', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Pharika\'s Libation', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Pheres-Band Centaurs', SETS.THEROS);
collection.addCard(3, 'Phyresis', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Phyrexian Arena', SETS.ALLWILLBEONE);
collection.addCard(1, 'Phyrexian Beast', 't'+SETS.ALLWILLBEONE, false, 6);
collection.addCard(3, 'Phyrexian Digester', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Phyrexian Driver', SETS.NEMESIS); 
collection.addCard(3, 'Phyrexian Hulk', SETS.CORE2013);
collection.addCard(1, 'Phyrexian Ingester', SETS.NEWPHYREXIA, true);
collection.addCard(3, 'Phyrexian Mite', 't'+SETS.ALLWILLBEONE, false, 11);
collection.addCard(1, 'Phyrexian Monitor', SETS.URZASDESTINY);
collection.addCard(1, 'Phyrexian Revoker', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Phyrexian Swarmlord', SETS.NEWPHYREXIA, true);

collection.addCard(1, 'Pieces of the Puzzle', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(2, 'Pilfering Hawk', SETS.KALDHEIM);
collection.addCard(1, 'Pillage', SETS.MODERNHORIZONS);
collection.addCard(3, 'Pillar of Flame', SETS.AVACYNRESTORED);
collection.addCard(1, 'Pillar of Flame', SETS.AVACYNRESTORED, true);
collection.addCard(1, 'Pillarfield Ox', SETS.CORE2013);
collection.addCard(1, 'Pincher Beetles', SETS.TENTH);
collection.addCard(1, 'Piston Sledge', SETS.MIRRODINBESIEGED);
collection.addCard(5, 'Pitchburn Devils', SETS.INNISTRAD);

collection.addCard(1, 'Plague Myr', SETS.MIRRODINBESIEGED);
collection.addCard(4, 'Plague Stinger', SETS.SCARSOFMIRRODIN);

collection.addCard(1, 'Plains', SETS.ALLWILLBEONE, false, 262);
collection.addCard(1, 'Plains', SETS.ALLWILLBEONE, true, 262);
collection.addCard(1, 'Plains', SETS.ALLWILLBEONE, false, 267);
collection.addCard(1, 'Plains', SETS.BATTLEFORZENDIKAR, false, 252);
collection.addCard(4, 'Plains', SETS.BLESSEDVSCURSED, false, 38);
collection.addCard(5, 'Plains', SETS.BLESSEDVSCURSED, false, 39);
collection.addCard(4, 'Plains', SETS.BLESSEDVSCURSED, false, 40);
collection.addCard(1, 'Plains', SETS.CORE2012, false, 232);
collection.addCard(1, 'Plains', SETS.CORE2012, false, 233);
collection.addCard(3, 'Plains', SETS.CORE2013, false, 230);
collection.addCard(3, 'Plains', SETS.CORE2013, false, 231);
collection.addCard(6, 'Plains', SETS.CORE2013, false, 232);
collection.addCard(1, 'Plains', SETS.CORE2013, false, 233);
collection.addCard(4, 'Plains', SETS.CORE2014, false, 230);
collection.addCard(4, 'Plains', SETS.CORE2014, false, 231);
collection.addCard(6, 'Plains', SETS.CORE2014, false, 232);
collection.addCard(5, 'Plains', SETS.CORE2014, false, 233);
collection.addCard(1, 'Plains', SETS.CORE2015, false, 250);
collection.addCard(2, 'Plains', SETS.INNISTRAD, false, 250);
collection.addCard(4, 'Plains', SETS.INNISTRAD, false, 251);
collection.addCard(1, 'Plains', SETS.INNISTRAD, false, 252);
collection.addCard(2, 'Plains', SETS.MIRRODINBESIEGED, false, 146);
collection.addCard(3, 'Plains', SETS.MIRRODINBESIEGED, false, 147);
collection.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 250);
collection.addCard(3, 'Plains', SETS.RETURNTORAVNICA, false, 251);
collection.addCard(3, 'Plains', SETS.RETURNTORAVNICA, false, 252);
collection.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 253);
collection.addCard(2, 'Plains', SETS.RETURNTORAVNICA, false, 254);
collection.addCard(5, 'Plains', SETS.THEROS, false, 230);
collection.addCard(7, 'Plains', SETS.THEROS, false, 231);
collection.addCard(4, 'Plains', SETS.THEROS, false, 232);
collection.addCard(6, 'Plains', SETS.THEROS, false, 233);
collection.addCard(11, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 283);
collection.addCard(10, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 284);
collection.addCard(8, 'Plains', SETS.SHADOWSOVERINNISTRAD, false, 285);
collection.addCard(3, 'Plains', SETS.SORINVSINNISTRAD, false, 39);
collection.addCard(2, 'Plains', SETS.SORINVSINNISTRAD, false, 40);
collection.addCard(1, 'Plains', SETS.THEROS, false, 230);
collection.addCard(1, 'Plains', SETS.ZENDIKAR, false, '231a');

collection.addCard(1, 'Planar Disruption', SETS.ALLWILLBEONE);
collection.addCard(1, 'Plated Seastrider', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Plated Wurm', SETS.PORTALSECONDAGE);
collection.addCard(1, 'Plow Through Reito', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(3, 'Plummet', SETS.BATTLEFORZENDIKAR);
collection.addCard(3, 'Plummet', SETS.CORE2012);
collection.addCard(1, 'Plummet', SETS.CORE2013);
collection.addCard(1, 'Plunder', SETS.TIMESPIRAL);

collection.addCard(1, 'Poison Counter', 't'+SETS.ALLWILLBEONE, false, 14);
collection.addCard(1, 'Poison the Cup', SETS.KALDHEIM);
collection.addCard(3, 'Polluted Dead', SETS.AVACYNRESTORED);
collection.addCard(4, 'Ponder', SETS.CORE2012);
collection.addCard(1, 'Porcelain Zealot', SETS.ALLWILLBEONE);
collection.addCard(3, 'Pore Over the Pages', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Port of Karfell', SETS.KALDHEIM);
collection.addCard(1, 'Power of Fire', SETS.SHADOWMOOR);
collection.addCard(1, 'Power Plant Worker', SETS.BROTHERSWAR);
collection.addCard(1, 'Powerstone', 't'+SETS.BROTHERSWAR, false, 7);

collection.addCard(1, 'Predation Steward', SETS.ALLWILLBEONE);
collection.addCard(4, 'Predator\'s Gambit', SETS.AVACYNRESTORED);
collection.addCard(1, 'Prescient Chimera', SETS.THEROS);
collection.addCard(1, 'Presence of Gond', SETS.MASTERS25);
collection.addCard(2, 'Press into Service', SETS.OATHOFTHEGATEWATCH);
collection.addCard(3, 'Prey Upon', SETS.CORE2013);
collection.addCard(2, 'Prey Upon', SETS.INNISTRAD);
collection.addCard(1, 'Price of Progress', SETS.FIREANDLIGHTNING);
collection.addCard(5, 'Pride Guardian', SETS.CORE2012);
collection.addCard(3, 'Priests of Norn', SETS.MIRRODINBESIEGED);
collection.addCard(2, 'Primal Clay', SETS.CORE2013);
collection.addCard(3, 'Primal Huntbeast', SETS.CORE2013);
collection.addCard(1, 'Primordial Hydra', SETS.CORE2012);
collection.addCard(1, 'Prismatic Strands', SETS.JUDGMENT);
collection.addCard(1, 'Prismwake Merrow', SETS.SHADOWMOOR);
collection.addCard(1, 'Pristine Talisman', SETS.NEWPHYREXIA);
collection.addCard(1, 'Prized Elephant', SETS.CORE2013);
collection.addCard(1, 'Promised Kannushi', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Prophetic Prism', SETS.ALLWILLBEONE);

collection.addCard(3, 'Psychic Miasma', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Psychosis Crawler', SETS.BROTHERSWARRETROARTIFACTS);
collection.addCard(1, 'Psychotic Haze', SETS.TORMENT);
collection.addCard(1, 'Psychotic Fury', SETS.DISSENSION);

collection.addCard(4, 'Public Execution', SETS.CORE2013);
collection.addCard(4, 'Puncture Blast', SETS.EVENTIDE);
collection.addCard(1, 'Puncturing Blow', SETS.HOUROFDEVISTATION);
collection.addCard(2, 'Puncturing Light', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Purify the Grave', SETS.INNISTRAD);
collection.addCard(1, 'Pursue Glory', SETS.AMONKHET);
collection.addCard(1, 'Pursuit of Flight', SETS.RETURNTORAVNICA);
collection.addCard(2, 'Putrid Goblin', SETS.MODERNHORIZONS);

collection.addCard(1, 'Pyre Hound', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Pyreheart Wolf', SETS.DARKASCENSION);
collection.addCard(1, 'Pyretic Ritual', SETS.CORE2011);
collection.addCard(1, 'Pyroblast', SETS.ETERNALMASTERS);
collection.addCard(1, 'Pyroclasm', SETS.EIGHTH);
collection.addCard(1, 'Pyroclastic Elemental', SETS.JUMPSTART);
collection.addCard(2, 'Pyroconvergence', SETS.RETURNTORAVNICA);
collection.addCard(4, 'Pyrostatic Pillar', SETS.SCOURGE);
