
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(1, 'Rabid Bite', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Rage Extractor', SETS.NEWPHYREXIA);
collection.addCard(1, 'Rage Thrower', SETS.INNISTRAD);
collection.addCard(2, 'Rage-Scarred Berserker', SETS.THEROSBEYONDDEATH);
collection.addCard(4, 'Raging Poltergeist', SETS.AVACYNRESTORED);
collection.addCard(1, 'Rain of Thorns', SETS.AVACYNRESTORED);
collection.addCard(2, 'Rakdos Carnarium', SETS.SORINVSINNISTRAD);
collection.addCard(1, 'Rakdos Shred-Freak', SETS.RETURNTORAVNICA);
collection.addCard(2, 'Rally the Peasants', SETS.INNISTRAD);
collection.addCard(1, 'Raiders\' Karve', SETS.KALDHEIM, true);
collection.addCard(1, 'Raiders\' Spoils', SETS.KHANSOFTARKIR);
collection.addCard(2, 'Rain of Rust', SETS.FIFTHDAWN);
collection.addCard(1, 'Raise Dead', SETS.EIGHTH);
collection.addCard(1, 'Rakshasa\'s Secret', SETS.KHANSOFTARKIR);
collection.addCard(1, 'Rally the Forces', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Ramosian Rally', SETS.MERCADIANMASQUES);
collection.addCard(4, 'Rampant Growth', SETS.CORE2012);
collection.addCard(1, 'Rancid Earth', SETS.TORMENT);
collection.addCard(4, 'Ranger\'s Guile', SETS.INNISTRAD);
collection.addCard(1, 'Rank Officer', SETS.MODERNHORIZONS);
collection.addCard(2, 'Ransack the Lab', SETS.MODERNHORIZONS);
collection.addCard(1, 'Rapid Hybridization', SETS.GATECRASH);
collection.addCard(1, 'Ratchet Bomb', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Rathi Trapper', SETS.TIMESPIRALREMASTERED);
collection.addCard(1, 'Rats\' Feast', SETS.JUDGMENT);
collection.addCard(3, 'Raven\'s Crime', SETS.EVENTIDE);
collection.addCard(1, 'Raven\'s Crime', SETS.EVENTIDE, true);
collection.addCard(2, 'Ravenous Demon', SETS.DARKASCENSION);
collection.addCard(1, 'Ravenous Giant', SETS.MODERNHORIZONS);
collection.addCard(1, 'Ravenous Necrotitan', SETS.ALLWILLBEONE);
collection.addCard(1, 'Ravenous Rats', SETS.CORE2013);
collection.addCard(2, 'Ravenous Rats', SETS.DUELSOFTHEPLANESWALKERS);
collection.addCard(1, 'Ravenous Rats', SETS.EIGHTH);
collection.addCard(1, 'Ray of Dissolution', SETS.THEROS);
collection.addCard(4, 'Ray of Revelation', SETS.DARKASCENSION);
collection.addCard(1, 'Ray of Revelation', SETS.JUDGMENT);
collection.addCard(1, 'Ray of Revelation', SETS.JUDGMENT, true);
collection.addCard(3, 'Razorfield Thresher', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Razorfin Abolisher', SETS.EVENTIDE);

collection.addCard(2, 'Read the Bones', SETS.ZENDIKARVSELDRAZI);
collection.addCard(3, 'Reap the Seagraf', SETS.DARKASCENSION);
collection.addCard(2, 'Rebel', 't'+SETS.ALLWILLBEONE, false, 5);
collection.addCard(1, 'Rebel Salvo', SETS.ALLWILLBEONE);
collection.addCard(1, 'Rebuild', SETS.MODERNHORIZONS);
collection.addCard(2, 'Rebuke', SETS.BLESSEDVSCURSED);
collection.addCard(4, 'Rebuke', SETS.INNISTRAD);
collection.addCard(1, 'Reckless Brute', SETS.CORE2013);
collection.addCard(1, 'Reckless Bushwhacker', SETS.OATHOFTHEGATEWATCH);
collection.addCard(2, 'Reckless Charge', SETS.MODERNHORIZONS);
collection.addCard(1, 'Reckless Reveler', SETS.BORNOFTHEGODS);
collection.addCard(4, 'Reclaim', SETS.CORE2012);
collection.addCard(1, 'Reconstructed Thopter', SETS.BROTHERSWAR);
collection.addCard(4, 'Recumbent Bliss', SETS.EVENTIDE);
collection.addCard(1, 'Red-Hot Hottie', SETS.UNHINGED);
collection.addCard(1, 'Redirect', SETS.CORE2013);
collection.addCard(1, 'Reduce to Ashes', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Reef Shaman', SETS.APOCALYPSE);
collection.addCard(1, 'Reflex Sliver', SETS.TIMESPIRALREMASTERED);
collection.addCard(1, 'Regenerate', SETS.CORE2010);
collection.addCard(1, 'Relentless Skaabs', SETS.BLESSEDVSCURSED);
collection.addCard(2, 'Relentless Skaabs', SETS.DARKASCENSION);
collection.addCard(1, 'Relic of Progenitus', SETS.SHARDSOFALARA);
collection.addCard(4, 'Relic Putrescence', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Remember the Fallen', SETS.NEWPHYREXIA);
collection.addCard(1, 'Remove Soul', SETS.EIGHTH);
collection.addCard(2, 'Rendclaw Trow', SETS.EVENTIDE);
collection.addCard(1, 'Renegade Demon', SETS.AVACYNRESTORED);
collection.addCard(2, 'Repeal', SETS.GUILDPACT);
collection.addCard(1, 'Replicating Ring', SETS.KALDHEIM);
collection.addCard(1, 'Requiem Angel', SETS.DARKASCENSION);
collection.addCard(1, 'Resistance Reunited', SETS.ALLWILLBEONE);
collection.addCard(1, 'Resistance Skywarden', SETS.ALLWILLBEONE);
collection.addCard(1, 'Resize', SETS.COLDSNAP);
collection.addCard(3, 'Resounding Thunder', SETS.SHARDSOFALARA);
collection.addCard(2, 'Restless Apparition', SETS.EVENTIDE);
collection.addCard(1, 'Restless Dreams', SETS.TORMENT);
collection.addCard(1, 'Restoration Angel', SETS.AVACYNRESTORED);
collection.addCard(1, 'Restore the Peace', SETS.DRAGONSMAZE);
collection.addCard(1, 'Return from Extinction', SETS.MODERNHORIZONS);
collection.addCard(1, 'Return to Nature', SETS.THEROSBEYONDDEATH);
collection.addCard(2, 'Returned Phalanx', SETS.THEROS);
collection.addCard(1, 'Revenge of the Hunted', SETS.AVACYNRESTORED);
collection.addCard(1, 'Reverent Hoplite', SETS.THEROSBEYONDDEATH);
collection.addCard(4, 'Revoke Existence', SETS.SCARSOFMIRRODIN);

collection.addCard(2, 'Rhox Veteran', SETS.MODERNHORIZONS);

collection.addCard(1, 'Riddle of Lightning', SETS.FUTURESIGHT);
collection.addCard(1, 'Rift Elemental', SETS.TIMESPIRALREMASTERED);
collection.addCard(4, 'Righteous Blow', SETS.AVACYNRESTORED);
collection.addCard(1, 'Ring of Evos Isle', SETS.CORE2013);
collection.addCard(1, 'Ring of Kalonia', SETS.CORE2013);
collection.addCard(1, 'Ring of Three Wishes', SETS.CORE2014);
collection.addCard(1, 'Ring of Thune', SETS.CORE2013);
collection.addCard(1, 'Ring of Xathrid', SETS.CORE2013);
collection.addCard(1, 'Ringskipper', SETS.LORWYN);
collection.addCard(1, 'Riot Control', SETS.DRAGONSMAZE);
collection.addCard(5, 'Riot Devils', SETS.INNISTRAD);
collection.addCard(3, 'Riot Ringleader', SETS.AVACYNRESTORED);
collection.addCard(1, 'Rise from the Grave', SETS.CORE2010);
collection.addCard(2, 'Rise from the Grave', SETS.CORE2013);
collection.addCard(1, 'Rite of Ruin', SETS.AVACYNRESTORED);
collection.addCard(4, 'Rite of the Serpent', SETS.KHANSOFTARKIR);
collection.addCard(4, 'Riverfall Mimic', SETS.EVENTIDE);
collection.addCard(1, 'Rix Maadi Reveler', SETS.RAVNICAALLEGIANCE);

collection.addCard(2, 'Roaring Primadox', SETS.CORE2013);
collection.addCard(1, 'Roc Egg', SETS.CORE2012);
collection.addCard(1, 'Roc Hunter', SETS.BROTHERSWAR);
collection.addCard(5, 'Rock Jockey', SETS.SCOURGE);
collection.addCard(1, 'Rocky Tar Pit', SETS.ZENDIKARVSELDRAZI);
collection.addCard(1, 'Rogue Kavu', SETS.NINTH);
collection.addCard(1, 'Roiling Waters', SETS.OATHOFTHEGATEWATCH);
collection.addCard(1, 'Rolling Temblor', SETS.INNISTRAD);
collection.addCard(1, 'Ronin Cavekeeper', SETS.SAVIORSOFKAMIGAWA);
collection.addCard(1, 'Ronom Serpent', SETS.COLDSNAP);
collection.addCard(1, 'Ronom Unicorn', SETS.COLDSNAP);
collection.addCard(1, 'Rooftop Storm', SETS.INNISTRAD);
collection.addCard(1, 'Rootbound Crag', SETS.CORE2013);
collection.addCard(1, 'Rot Wolf', SETS.MIRRODINBESIEGED);
collection.addCard(2, 'Rotcrown Ghoul', SETS.AVACYNRESTORED);
collection.addCard(1, 'Rotted Hystrix', SETS.NEWPHYREXIA);
collection.addCard(2, 'Rotting Fensnake', SETS.INNISTRAD);
collection.addCard(6, 'Rotting Mastodon', SETS.KHANSOFTARKIR);
collection.addCard(1, 'Rotwidow Pack', SETS.MODERNHORIZONS);
collection.addCard(1, 'Royal Assassin', SETS.CORE2012);

collection.addCard(1, 'Rubbleback Rhino', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Rubblebelt Maaka', SETS.DRAGONSMAZE);
collection.addCard(1, 'Rugged Highlands', SETS.ETERNALMASTERS);
collection.addCard(1, 'Ruin Processor', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Ruination Rioter', SETS.MODERNHORIZONS);
collection.addCard(1, 'Rumbling Baloth', SETS.CORE2014);
collection.addCard(1, 'Rumbling Sentry', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Rummaging Goblin', SETS.COMMANDERLEGENDS);
collection.addCard(1, 'Rummaging Goblin', SETS.CORE2013);
collection.addCard(1, 'Run Amok', SETS.KALDHEIM);
collection.addCard(1, 'Run Ashore', SETS.KALDHEIM);
collection.addCard(1, 'Rune Snag', SETS.COLDSNAP);
collection.addCard(1, 'Runechanter\'s Pike', SETS.INNISTRAD);
collection.addCard(2, 'Runeclaw Bear', SETS.CORE2012);
collection.addCard(1, 'Runeclaw Bear', SETS.CORE2012, true);
collection.addCard(1, 'Runed Servitor', SETS.ZENDIKARVSELDRAZI);
collection.addCard(1, 'Runewing', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Runic Repetition', SETS.INNISTRAD);
collection.addCard(1, 'Rush of Blood', SETS.AVACYNRESTORED );
collection.addCard(1, 'Rush of Knowledge', SETS.SCOURGE);
collection.addCard(1, 'Rushwood Dryad', SETS.TENTH);
collection.addCard(4, 'Russet Wolves', SETS.DARKASCENSION);
collection.addCard(1, 'Rusted Sentinel', SETS.CORE2012);
collection.addCard(2, 'Rusted Slasher', SETS.MIRRODINBESIEGED);
collection.addCard(2, 'Rustvine Cultivator', SETS.ALLWILLBEONE, false, 295);
collection.addCard(1, 'Ruthless Invasion', SETS.NEWPHYREXIA);
collection.addCard(1, 'Ruthless Predation', SETS.ALLWILLBEONE);
collection.addCard(3, 'Ruthless Ripper', SETS.KHANSOFTARKIR);
