
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(4, 'Saberclaw Golem', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(6, 'Sacred Wolf', SETS.CORE2012);
COLLECTION.addCard(1, 'Sadistic Obsession', SETS.MODERNHORIZONS);
COLLECTION.addCard(3, 'Safe Passage', SETS.CORE2013);
COLLECTION.addCard(1, 'Sage\'s Row Savant', SETS.JUMPSTART);
COLLECTION.addCard(1, 'Sage of Epityr', SETS.TIMESPIRAL);
COLLECTION.addCard(3, 'Saheeli, Sublime Artificer', SETS.WAROFTHESPARK);
COLLECTION.addCard(1, 'Sakura-Tribe Scout', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Samut, Tyrant Smasher', SETS.WAROFTHESPARK);
COLLECTION.addCard(5, 'Sanctuary Cat', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Sangrophage', SETS.TIMESPIRALREMASTERED);
COLLECTION.addCard(3, 'Sanguinary Mage', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Sanitarium Skeleton', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Saproling', 't'+SETS.CORE2012, false, 5);
COLLECTION.addCard(1, 'Satyr Rambler', SETS.THEROS);
COLLECTION.addCard(2, 'Savage Alliance', SETS.ELDRITCHMOON);
COLLECTION.addCard(1, 'Savage Surge', SETS.THEROS);
COLLECTION.addCard(5, 'Saving Grasp', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Sawblade Scamp', SETS.ALLWILLBEONE);
COLLECTION.addCard(3, 'Sawblade Scamp', SETS.ALLWILLBEONE, false, 292);

COLLECTION.addCard(3, 'Scalding Devil', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Scarecrone', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Scatter Ray', SETS.BROTHERSWAR);
COLLECTION.addCard(2, 'Scattershot', SETS.SCOURGE);
COLLECTION.addCard(5, 'Scorch the Fields', SETS.DARKASCENSION);
COLLECTION.addCard(4, 'Scoria Elemental', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Scorn Effigy', SETS.KALDHEIM, true);
COLLECTION.addCard(1, 'Scornful Egotist', SETS.SCOURGE);
COLLECTION.addCard(2, 'Scour from Existence', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Scourge Devil', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(1, 'Scourge of Geier Reach', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Scourge Servant', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Scourgemark', SETS.THEROS);
COLLECTION.addCard(1, 'Scrambleverse', SETS.CORE2012);
COLLECTION.addCard(1, 'Scrap Welder', SETS.KAMIGAWANEONDYNASTY);
COLLECTION.addCard(1, 'Scrapdiver Serpent', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Scrapskin Drake', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Scrapskin Drake', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(3, 'Screaming Fury', SETS.FIFTHDAWN);
COLLECTION.addCard(4, 'Screeching Silcaw', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(9, 'Screeching Skaab', SETS.DARKASCENSION);
COLLECTION.addCard(4, 'Scroll of Avacyn', SETS.AVACYNRESTORED);
COLLECTION.addCard(5, 'Scroll of Griselbrand', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Scroll Thief', SETS.CORE2011);
COLLECTION.addCard(2, 'Scroll Thief', SETS.CORE2013);
COLLECTION.addCard(1, 'Scroll Thief', SETS.CORE2014);
COLLECTION.addCard(1, 'Sculptor of Winter', SETS.KALDHEIM);

COLLECTION.addCard(1, 'Seacoast Drake', SETS.CORE2014);
COLLECTION.addCard(1, 'Seagraf Skaab', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Seal of Doom', SETS.NEMESIS);
COLLECTION.addCard(1, 'Seal of Removal', SETS.NEMESIS);
COLLECTION.addCard(4, 'Searchlight Geist', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Searing Spear', SETS.CORE2013);
COLLECTION.addCard(4, 'Second Guess', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Second Thoughts', SETS.ETERNALMASTERS, true);
COLLECTION.addCard(1, 'Seek the Wilds', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Seer\'s Lantern', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(2, 'Seething Pathblazer', SETS.MORNINGTIDE);
COLLECTION.addCard(1, 'Seismic Shudder', SETS.ZENDIKAR);
COLLECTION.addCard(1, 'Seismic Stomp', SETS.CORE2014);
COLLECTION.addCard(2, 'Seismic Strike', SETS.CORE2010);
COLLECTION.addCard(1, 'Selesnya Keyrune', SETS.RETURNTORAVNICA);
COLLECTION.addCard(3, 'Selfless Cathar', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Sell-Sword Brute', SETS.RAVNICACITYOFGUILDS);
COLLECTION.addCard(2, 'Seller of Songbirds', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Semblance Anvil', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Sengir Vampire', SETS.CORE2012);
COLLECTION.addCard(1, 'Sengir Vampire', SETS.WELCOME2016);
COLLECTION.addCard(4, 'Sensory Deprivation', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Sentinel Sliver', SETS.CORE2014);
COLLECTION.addCard(1, 'Sentinel Spider', SETS.CORE2013);
COLLECTION.addCard(1, 'Sentinels of Glen Elendra', SETS.LORWYN);
COLLECTION.addCard(1, 'Septic Rats', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Seraph of Dawn', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Seraph Sanctuary', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Serpent\'s Gift', SETS.CORE2013, true);
COLLECTION.addCard(1, 'Serra Angel', SETS.WELCOME2016);
COLLECTION.addCard(1, 'Serum Raker', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Serum Snare', SETS.ALLWILLBEONE);
COLLECTION.addCard(5, 'Servant of Nefarox', SETS.CORE2013);
COLLECTION.addCard(1, 'Servant of Tymaret', SETS.BORNOFTHEGODS);
COLLECTION.addCard(1, 'Setessan Oathsworn', SETS.BORNOFTHEGODS);
COLLECTION.addCard(1, 'Setessan Skirmisher', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Settle Beyond Reality', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Sever the Bloodline', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Severed Legion', SETS.DUELSOFTHEPLANESWALKERS);

COLLECTION.addCard(1, 'Shadowborn Apostle', SETS.CORE2014);
COLLECTION.addCard(1, 'Shadowmage Infiltrator', SETS.ODYSSEY);
COLLECTION.addCard(2, 'Shamble Back', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Shambling Attendants', SETS.KHANSOFTARKIR);
COLLECTION.addCard(1, 'Shambling Remains', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(2, 'Shard of Broken Glass', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Shard Volley', SETS.MORNINGTIDE);
COLLECTION.addCard(1, 'Sharpened Pitchfork', SETS.INNISTRAD);
COLLECTION.addCard(6, 'Shatter', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Shattered Angel', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Shattered Perception', SETS.DARKASCENSION);
COLLECTION.addCard(2, 'Sheer Drop', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(7, 'Shell Skulkin', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Shelter', SETS.ETERNALMASTERS);
COLLECTION.addCard(4, 'Sheltering Word', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Sheoldred\'s Edict', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Shimian Specter', SETS.CORE2013);
COLLECTION.addCard(1, 'Shimmer Myr', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(2, 'Shinen of Life\'s Roar', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Shinen of Fury\'s Fire', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Shipwreck Singer', SETS.THEROS);
COLLECTION.addCard(1, 'Shivan Dragon', SETS.CORE2010);
COLLECTION.addCard(1, 'Shivan Dragon', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(4, 'Shock', SETS.CORE2012);
COLLECTION.addCard(5, 'Shock', SETS.CORE2014);
COLLECTION.addCard(1, 'Shock Troops', SETS.EIGHTH);
COLLECTION.addCard(5, 'Shorecrasher Mimic', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Shoreline Ranger', SETS.SCOURGE);
COLLECTION.addCard(1, 'Show of Valor', SETS.CORE2013);
COLLECTION.addCard(4, 'Shriekgeist', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Shrine of Limitless Power', SETS.NEWPHYREXIA, true);

COLLECTION.addCard(1, 'Sickleslicer', SETS.NEWPHYREXIA);
COLLECTION.addCard(2, 'Sidisi\'s Pet', SETS.KHANSOFTARKIR);
COLLECTION.addCard(4, 'Sightless Ghoul', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Sign in Blood', SETS.CORE2013);
COLLECTION.addCard(1, 'Silburlind Snapper', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Silence', SETS.CORE2011);
COLLECTION.addCard(1, 'Silent Departure', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Silent Observer', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Silumgar Scavenger', SETS.MODERNHORIZONS);
COLLECTION.addCard(4, 'Silver Knight', SETS.SCOURGE);
COLLECTION.addCard(4, 'Silver Myr', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Silver-Inlaid Dagger', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Silvercoat Lion', SETS.CORE2013);
COLLECTION.addCard(1, 'Silverchase Fox', SETS.INNISTRAD);
COLLECTION.addCard(4, 'Silverclaw Griffin', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Silverfur Partisan', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Silvergill Douser', SETS.LORWYN);
COLLECTION.addCard(1, 'Silverskin Armor', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Simic Charm', SETS.GATECRASH);
COLLECTION.addCard(1, 'Sinew Dancer', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Sinew Sliver', SETS.TIMESPIRALREMASTERED);
COLLECTION.addCard(2, 'Sinister Possession', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Sink into Takenuma', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Sip of Hemlock', SETS.THEROS);

COLLECTION.addCard(3, 'Skaab Goliath', SETS.INNISTRAD);
COLLECTION.addCard(4, 'Skeletal Grimace', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Skemfar Elderhall', SETS.KALDHEIM);
COLLECTION.addCard(6, 'Skillful Lunge', SETS.DARKASCENSION);
COLLECTION.addCard(2, 'Skinrender', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Skirsdag Cultist', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Skirsdag Flayer', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Skola Grovedancer', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Sky Spirit', SETS.CONSPIRACY);
COLLECTION.addCard(1, 'Sky-Eel School', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Skyrider Elf', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Skyscythe Engulfer', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Skyscythe Engulfer', SETS.ALLWILLBEONE, true);
COLLECTION.addCard(1, 'Skyshroud Ranger', SETS.TENTH);
COLLECTION.addCard(1, 'Skystrike Officer', SETS.BROTHERSWAR, true);
COLLECTION.addCard(4, 'Skywinder Drake', SETS.CORE2012);

COLLECTION.addCard(4, 'Slaughter Cry', SETS.CORE2012);
COLLECTION.addCard(1, 'Slaughter Singer', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'Slayer of the Wicked', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Slayers\' Stronghold', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Sleep', SETS.CORE2011);
COLLECTION.addCard(1, 'Sleep of the Dead', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(2, 'Sleep Paralysis', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Slice in Twain', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Slime Molding', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Slip Through Space', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(2, 'Slippery Bogle', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Slipstream Serpent', SETS.TIMESPIRAL);
COLLECTION.addCard(2, 'Sliver Construct', SETS.CORE2014);
COLLECTION.addCard(3, 'Slum Reaper', SETS.RETURNTORAVNICA);

COLLECTION.addCard(1, 'Smallpox', SETS.CORE2012);
COLLECTION.addCard(1, 'Smash', SETS.RAVNICACITYOFGUILDS);
COLLECTION.addCard(1, 'Smash', SETS.TENTH);
COLLECTION.addCard(3, 'Smash to Smithereens', SETS.SHADOWMOOR);
COLLECTION.addCard(1, 'Smelt', SETS.CORE2013);
COLLECTION.addCard(1, 'Smog Elemental', SETS.GATECRASH);
COLLECTION.addCard(1, 'Smoke Shroud', SETS.MODERNHORIZONS);
COLLECTION.addCard(4, 'Smoldering Butcher', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Smother', SETS.ZENDIKARVSELDRAZI);

COLLECTION.addCard(1, 'Snapsail Glider', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(4, 'Snare the Skies', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Sneak Attack', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Sneaky Homunculus', SETS.EIGHTH);

COLLECTION.addCard(1, 'Sokenzan Spellblade', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(1, 'Solemn Offering', SETS.CORE2011);
COLLECTION.addCard(1, 'Solitary Hunter', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(3, 'Soliton', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Somberwald Dryad', SETS.DARKASCENSION);
COLLECTION.addCard(3, 'Somberwald Spider', SETS.INNISTRAD);
COLLECTION.addCard(3, 'Somberwald Vigilante', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Soot Imp', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Soratami Mirror-Guard', SETS.CHAMPIONSOFKAMIGAWA);
COLLECTION.addCard(1, 'Sorcerer\'s Strongbox', SETS.CORE2011);
COLLECTION.addCard(3, 'Sorin\'s Thirst', SETS.CORE2012);
COLLECTION.addCard(1, 'Sorin, Lord of Innistrad', SETS.SORINVSINNISTRAD, true);
COLLECTION.addCard(1, 'Soul Bleed', SETS.CORE2010);
COLLECTION.addCard(1, 'Soul of the Harvest', SETS.WELCOME2016);
COLLECTION.addCard(2, 'Soul Reap', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Soul Seizer', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Soul Snuffers', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Soul-Guide Lantern', SETS.BROTHERSWARRETROARTIFACTS);
COLLECTION.addCard(1, 'Soul\'s Grace', SETS.SHARDSOFALARA);
COLLECTION.addCard(1, 'Soul\'s Might', SETS.COMMANDERLEGENDS);
COLLECTION.addCard(1, 'Soulbright Flamekin', SETS.LORWYN);
COLLECTION.addCard(4, 'Soulcage Fiend', SETS.AVACYNRESTORED);

COLLECTION.addCard(2, 'Spare from Evil', SETS.INNISTRAD);
COLLECTION.addCard(6, 'Spark Elemental', SETS.FIFTHDAWN);
COLLECTION.addCard(1, 'Spark Elemental', SETS.FIREANDLIGHTNING, true);
COLLECTION.addCard(2, 'Spark Jolt', SETS.THEROS);
COLLECTION.addCard(3, 'Spark Spray', SETS.SCOURGE);
COLLECTION.addCard(2, 'Sparkmage\'s Gambit', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(5, 'Spawning Breath', SETS.RISEOFTHEELDRAZI);
COLLECTION.addCard(1, 'Spawnwrithe', SETS.JACEVSVRASKA);
COLLECTION.addCard(4, 'Spectral Flight', SETS.INNISTRAD);
COLLECTION.addCard(7, 'Spectral Gateguards', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Spectral Grasp', SETS.CONSPIRACYTAKETHECROWN);
COLLECTION.addCard(4, 'Spectral Prison', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Spectral Procession', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(2, 'Spell Snuff', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Sphinx of Magosi', SETS.WELCOME2016);
COLLECTION.addCard(1, 'Sphinx of Uthuun', SETS.CORE2012);
COLLECTION.addCard(2, 'Spidery Grasp', SETS.INNISTRAD);
COLLECTION.addCard(7, 'Spiked Baloth', SETS.CORE2013);
COLLECTION.addCard(1, 'Spikeshot Elder', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(3, 'Spiketail Drakeling', SETS.TIMESPIRAL);
COLLECTION.addCard(1, 'Spin Engine', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Spinehorn Minotaur', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Spineless Thug', SETS.NEMESIS);
COLLECTION.addCard(3, 'Spire Monitor', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Spire Monitor', SETS.NEWPHYREXIA, true);
COLLECTION.addCard(4, 'Spire Serpent', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Spirit', SETS.BLESSEDVSCURSED, false, 79);
COLLECTION.addCard(3, 'Spirit', 't'+SETS.SHADOWSOVERINNISTRAD, false, 3);
COLLECTION.addCard(1, 'Spirit Away', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Spitemare', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Spiteful Bully', SETS.NEMESIS);
COLLECTION.addCard(1, 'Spiteful Motives', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Spiteful Returned', SETS.BORNOFTHEGODS);
COLLECTION.addCard(4, 'Spiteful Shadows', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Splatter Thug', SETS.ICONICMASTERS);
COLLECTION.addCard(1, 'Splicer\'s Skill', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Splinterfright', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Spore Frog', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Sporemound', SETS.CORE2014);
COLLECTION.addCard(1, 'Spread the Sickness', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Springbloom Druid', SETS.MODERNHORIZONS);

COLLECTION.addCard(1, 'Squelching Leeches', SETS.JOURNEYINTONYX);

COLLECTION.addCard(1, 'Staff of the Death Magus', SETS.CORE2014);
COLLECTION.addCard(1, 'Staggering Insight', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Stalwart Valkyrie', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Stampede Rider', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(2, 'Starlit Mantle', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Stasis Snare', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Staunch-Hearted Warrior', SETS.THEROS);
COLLECTION.addCard(1, 'Stealer of Secrets', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Steamcore Weird', SETS.GUILDPACT);
COLLECTION.addCard(2, 'Steel Sabotage', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Steeple Roc', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Stensia Innkeeper', SETS.ELDRITCHMOON);
COLLECTION.addCard(1, 'Stern Dismissal', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Stern Mentor', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Stingerfling Spider', SETS.CORE2012);
COLLECTION.addCard(2, 'Stingmoggie', SETS.MORNINGTIDE);
COLLECTION.addCard(1, 'Stingscourger', SETS.ETERNALMASTERS);
COLLECTION.addCard(3, 'Stinkdrinker Daredevil', SETS.LORWYN);
COLLECTION.addCard(1, 'Stir the Sands', SETS.AMONKHET);
COLLECTION.addCard(1, 'Stirring Address', SETS.MODERNHORIZONS);
COLLECTION.addCard(2, 'Stitched Drake', SETS.INNISTRAD);
COLLECTION.addCard(5, 'Stitched Drake', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Stitched Mangler', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Stitcher\'s Apprentice', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Stoic Rebuttal', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Stone Haven Medic', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Stone Quarry', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Stone Rain', SETS.EIGHTH);
COLLECTION.addCard(1, 'Stonewright', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Stony Silence', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Storm Crow', SETS.EIGHTH);
COLLECTION.addCard(3, 'Stormblood Berserker', SETS.CORE2012);
COLLECTION.addCard(4, 'Stormbound Geist', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Stormfront Pegasus', SETS.CORE2011);
COLLECTION.addCard(1, 'Stormrider Spirit', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Storvald, Frost Giant Jarl', SETS.FORGOTTENREALMSCOMMANDER, true);
COLLECTION.addCard(2, 'Strangleroot Geist', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Strangling Soot', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(4, 'Stream Hopper', SETS.EVENTIDE);
COLLECTION.addCard(2, 'Stream of Thought', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Streambed Aquitects', SETS.LORWYN);
COLLECTION.addCard(1, 'Strength in Numbers', SETS.MODERNMASTERS2017);
COLLECTION.addCard(3, 'Strider Harness', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'String of Disappearances', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Stromkirk Captain', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Stupefying Touch', SETS.TORMENT);
COLLECTION.addCard(1, 'Sturmgeist', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Sturmgeist', SETS.INNISTRAD, true);

COLLECTION.addCard(1, 'Su-Chi Cave Guard', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Submerged Boneyard', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(1, 'Sudden Disappearance', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Sulfur Falls', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Sulfuric Vortex', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(6, 'Sultai Scavenger', SETS.KHANSOFTARKIR);
COLLECTION.addCard(1, 'Sunspire Gatekeepers', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Sunspire Griffin', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Suntail Hawk', SETS.CORE2014);
COLLECTION.addCard(1, 'Sure Strike', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Sure Strike', SETS.CORE2021);
COLLECTION.addCard(3, 'Surging Aether', SETS.COLDSNAP);
COLLECTION.addCard(1, 'Surging Dementia', SETS.COLDSNAP);
COLLECTION.addCard(4, 'Surging Flame', SETS.COLDSNAP);
COLLECTION.addCard(1, 'Surging Might', SETS.COLDSNAP);
COLLECTION.addCard(1, 'Survivor of the Unseen', SETS.COLDSNAP);

COLLECTION.addCard(2, 'Svella, Ice Shaper', SETS.KALDHEIM);

COLLECTION.addCard(4, 'Swamp', SETS.BLESSEDVSCURSED, false, 74);
COLLECTION.addCard(4, 'Swamp', SETS.BLESSEDVSCURSED, false, 75);
COLLECTION.addCard(4, 'Swamp', SETS.BLESSEDVSCURSED, false, 76);
COLLECTION.addCard(1, 'Swamp', SETS.BROTHERSWAR, false, 272);
COLLECTION.addCard(1, 'Swamp', SETS.BROTHERSWAR, false, 273);
COLLECTION.addCard(2, 'Swamp', SETS.CORE2012, false, 239);
COLLECTION.addCard(1, 'Swamp', SETS.CORE2013, false, 238);
COLLECTION.addCard(1, 'Swamp', SETS.CORE2013, false, 239);
COLLECTION.addCard(1, 'Swamp', SETS.CORE2013, false, 241);
COLLECTION.addCard(5, 'Swamp', SETS.CORE2014, false, 238);
COLLECTION.addCard(2, 'Swamp', SETS.CORE2014, false, 239);
COLLECTION.addCard(5, 'Swamp', SETS.CORE2014, false, 240);
COLLECTION.addCard(6, 'Swamp', SETS.CORE2014, false, 241);
COLLECTION.addCard(2, 'Swamp', SETS.INNISTRAD, false, 256);
COLLECTION.addCard(1, 'Swamp', SETS.INNISTRAD, false, 257);
COLLECTION.addCard(2, 'Swamp', SETS.INNISTRAD, false, 258);
COLLECTION.addCard(1, 'Swamp', SETS.IZZETVSGOLGARI, false, 85);
COLLECTION.addCard(4, 'Swamp', SETS.RETURNTORAVNICA, false, 260);
COLLECTION.addCard(2, 'Swamp', SETS.RETURNTORAVNICA, false, 261);
COLLECTION.addCard(1, 'Swamp', SETS.RETURNTORAVNICA, false, 262);
COLLECTION.addCard(2, 'Swamp', SETS.RETURNTORAVNICA, false, 264);
COLLECTION.addCard(9, 'Swamp', SETS.SHADOWSOVERINNISTRAD, false, 289);
COLLECTION.addCard(10, 'Swamp', SETS.SHADOWSOVERINNISTRAD, false, 290);
COLLECTION.addCard(11, 'Swamp', SETS.SHADOWSOVERINNISTRAD, false, 291);
COLLECTION.addCard(1, 'Swamp', SETS.SORINVSINNISTRAD, false, 35);
COLLECTION.addCard(1, 'Swamp', SETS.SORINVSINNISTRAD, false, 36);
COLLECTION.addCard(1, 'Swamp', SETS.SORINVSINNISTRAD, false, 37);
COLLECTION.addCard(2, 'Swamp', SETS.SORINVSINNISTRAD, false, 78);
COLLECTION.addCard(1, 'Swamp', SETS.SORINVSINNISTRAD, false, 79);
COLLECTION.addCard(2, 'Swamp', SETS.SORINVSINNISTRAD, false, 80);
COLLECTION.addCard(4, 'Swamp', SETS.THEROS, false, 238);
COLLECTION.addCard(5, 'Swamp', SETS.THEROS, false, 239);
COLLECTION.addCard(8, 'Swamp', SETS.THEROS, false, 240);
COLLECTION.addCard(7, 'Swamp', SETS.THEROS, false, 241);
COLLECTION.addCard(5, 'Swamp', SETS.ZENDIKARVSELDRAZI, false, 70);
COLLECTION.addCard(4, 'Swamp', SETS.ZENDIKARVSELDRAZI, false, 71);
COLLECTION.addCard(4, 'Swamp', SETS.ZENDIKARVSELDRAZI, false, 72);

COLLECTION.addCard(1, 'Swarm of Bloodflies', SETS.KHANSOFTARKIR);
COLLECTION.addCard(2, 'Sweep Away', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(1, 'Swell of Growth', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Swift Justice', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Swift Warkite', SETS.DRAGONSOFTARKIR);
COLLECTION.addCard(1, 'Swiftgear Drake', SETS.BROTHERSWAR, true);
COLLECTION.addCard(1, 'Switcheroo', SETS.CORE2013);
COLLECTION.addCard(1, 'Swooping Lookout', SETS.ALLWILLBEONE);

COLLECTION.addCard(1, 'Sylvan Might', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Sylvok Battle-Chair', SETS.ALLWILLBEONE);
COLLECTION.addCard(4, 'Sylvok Lifestaff', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Sylvok Replica', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Symmetry Matrix', SETS.BROTHERSWAR);
