
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(1, 'Tainted Field', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(4, 'Tainted Strike', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Tajuru Pathwarden', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(4, 'Talara\'s Bane', SETS.EVENTIDE);
COLLECTION.addCard(6, 'Talons of Falkenrath', SETS.DARKASCENSION);
COLLECTION.addCard(2, 'Tandem Lookout', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Tandem Tactics', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(2, 'Tangle Angler', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(3, 'Tangle Mantis', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Taranika, Akroan Veteran', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(3, 'Tarfire', SETS.LORWYN);
COLLECTION.addCard(2, 'Taste of Blood', SETS.CORE2012);

COLLECTION.addCard(1, 'Teething Wurmlet', SETS.BROTHERSWAR);
COLLECTION.addCard(4, 'Tel-Jilad Defiance', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Tel-Jilad Outrider', SETS.DARKSTEEL);
COLLECTION.addCard(1, 'Tempered Steel', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Temporal Fissure', SETS.SCOURGE);
COLLECTION.addCard(2, 'Tenement Crasher', SETS.RETURNTORAVNICA);
COLLECTION.addCard(3, 'Tendrils of Corruption', SETS.CORE2010);
COLLECTION.addCard(1, 'Tergrid\'s Shadow', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Terminate', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(1, 'Terminus', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Terramorphic Expanse', SETS.PHYREXIAVSCOALITION);
COLLECTION.addCard(4, 'Terrifying Presence', SETS.AVACYNRESTORED);
COLLECTION.addCard(4, 'Terror', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(2, 'Teyo, the Shieldmage', SETS.WAROFTHESPARK);
COLLECTION.addCard(1, 'Teysa, Envoy of Ghosts', SETS.DRAGONSMAZE, true);

COLLECTION.addCard(1, 'Thalia, Guardian of Thraben', SETS.DARKASCENSION);
COLLECTION.addCard(3, 'Thatcher Revolt', SETS.AVACYNRESTORED);
COLLECTION.addCard(2, 'The Autonomous Furnace', SETS.ALLWILLBEONE);
COLLECTION.addCard(2, 'The Binding of the Titans', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'The Dross Pits', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'The Fall of Kroog', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'The Hunter Maze', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'The Three Seasons', SETS.KALDHEIM);
COLLECTION.addCard(1, 'The Triumph of Anax', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'The Wanderer', SETS.WAROFTHESPARK);
COLLECTION.addCard(4, 'Think Twice', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Third Path Savant', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Thirst for Meaning', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(2, 'Thirsting Roots', SETS.ALLWILLBEONE);
COLLECTION.addCard(3, 'Thorn-Thrash Viashino', SETS.SHARDSOFALARA);
COLLECTION.addCard(1, 'Thornado', SETS.MODERNHORIZONS);
COLLECTION.addCard(2, 'Thornhide Wolves', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Thornwood Falls', SETS.ETERNALMASTERS);
COLLECTION.addCard(4, 'Thought Scour', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Thraben Heretic', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Thraben Inspector', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Thraben Purebloods', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Thraben Sentry', SETS.INNISTRAD);
COLLECTION.addCard(4, 'Thraben Valiant', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Thrash of Raptors', SETS.IXALAN);
COLLECTION.addCard(1, 'Thrill of Possibility', SETS.CORE2021);
COLLECTION.addCard(1, 'Thrill of Possibility', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Thrill-Kill Assassin', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Throne of Empires', SETS.CORE2012, true);
COLLECTION.addCard(2, 'Throttle', SETS.KHANSOFTARKIR);
COLLECTION.addCard(1, 'Thrull Parasite', SETS.GATECRASH);
COLLECTION.addCard(3, 'Thrummingbird', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(4, 'Thunderbolt', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Thunderbolt', SETS.FIREANDLIGHTNING, true);
COLLECTION.addCard(1, 'Thunderous Might', SETS.BORNOFTHEGODS);
COLLECTION.addCard(1, 'Thunderous Wrath', SETS.AVACYNRESTORED);

COLLECTION.addCard(2, 'Tibalt, Rakish Instigator', SETS.WAROFTHESPARK);
COLLECTION.addCard(1, 'Tibalt, the Fiend-Blooded', SETS.SORINVSINNISTRAD, true);
COLLECTION.addCard(5, 'Tilling Treefolk', SETS.EVENTIDE);
COLLECTION.addCard(2, 'Timber Gorge', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(4, 'Timberland Guide', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Timely Reinforcements', SETS.CORE2012, true);
COLLECTION.addCard(1, 'Timely Reinforcements', SETS.CORE2012);
COLLECTION.addCard(1, 'Tin Street Hooligan', SETS.GUILDPACT);
COLLECTION.addCard(1, 'Tine Shrike', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(1, 'Titanic Growth', SETS.ALLWILLBEONE);
COLLECTION.addCard(6, 'Titanic Growth', SETS.CORE2012);
COLLECTION.addCard(6, 'Titanic Growth', SETS.CORE2013);
COLLECTION.addCard(3, 'Tithe Drinker', SETS.DRAGONSMAZE);

COLLECTION.addCard(2, 'Tolarian Sentinel', SETS.TIMESPIRAL);
COLLECTION.addCard(1, 'Tomakul Scrapsmith', SETS.BROTHERSWAR);
COLLECTION.addCard(1, 'Tome Scour', SETS.CORE2010);
COLLECTION.addCard(1, 'Tooth Collector', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Topple', SETS.NEMESIS);
COLLECTION.addCard(1, 'Topplegeist', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Torch Drake', SETS.GUILDPACT);
COLLECTION.addCard(1, 'Torch Fiend', SETS.CORE2013);
COLLECTION.addCard(1, 'Torch Fiend', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Torch Slinger', SETS.ZENDIKARVSELDRAZI);
COLLECTION.addCard(1, 'Torii Watchward', SETS.SAVIORSOFKAMIGAWA);
COLLECTION.addCard(3, 'Tormented Soul', SETS.CORE2012);
COLLECTION.addCard(2, 'Tormented Soul', SETS.CORE2013);
COLLECTION.addCard(1, 'Tormenting Voice', SETS.AMONKHET);
COLLECTION.addCard(1, 'Tormenting Voice', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(3, 'Torrent of Fire', SETS.SCOURGE);
COLLECTION.addCard(1, 'Touch of Death', SETS.ICEAGE);
COLLECTION.addCard(1, 'Touch of the Eternal', SETS.CORE2013);
COLLECTION.addCard(1, 'Touch of the Void', SETS.BATTLEFORZENDIKAR);
COLLECTION.addCard(1, 'Tower Geist', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Towering Indrik', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Towering-Wave Mystic', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Toxic Stench', SETS.JUDGMENT);

COLLECTION.addCard(3, 'Tracker\'s Instincts', SETS.DARKASCENSION);
COLLECTION.addCard(4, 'Tragic Slip', SETS.DARKASCENSION);
COLLECTION.addCard(2, 'Train of Thought', SETS.GUILDPACT);
COLLECTION.addCard(4, 'Traitorous Blood', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Traitorous Instinct', SETS.RETURNTORAVNICA);
COLLECTION.addCard(4, 'Tranquil Cove', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Tranquil Cove', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Tranquil Expanse', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(1, 'Transcendent Envoy', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(3, 'Transguild Promenade', SETS.RETURNTORAVNICA);
COLLECTION.addCard(1, 'Trapjaw Kelpie', SETS.EVENTIDE);
COLLECTION.addCard(4, 'Travel Preparations', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Traveler\'s Cloak', SETS.INVASION);
COLLECTION.addCard(1, 'Treasure Hunter', SETS.TENTH);
COLLECTION.addCard(1, 'Treefolk Umbra', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Treetop Bracers', SETS.NEMESIS);
COLLECTION.addCard(1, 'Tribute to Hunger', SETS.BLESSEDVSCURSED);
COLLECTION.addCard(1, 'Tribute to Hunger', SETS.INNISTRAD);
COLLECTION.addCard(1, 'Trickery Charm', SETS.ONSLAUGHT);
COLLECTION.addCard(2, 'Tricks of the Trade', SETS.CORE2013);
COLLECTION.addCard(1, 'Tricks of the Trade', SETS.CORE2013, true);
COLLECTION.addCard(2, 'Trickster Mage', SETS.NEMESIS);
COLLECTION.addCard(1, 'Trigon of Infestation', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(3, 'Trinket Mage', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Triplicate Spirits', SETS.CORE2015);
COLLECTION.addCard(1, 'Triton Tactics', SETS.THEROS);
COLLECTION.addCard(1, 'Triton Waverider', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(2, 'Triumph of Ferocity', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Troll Ascetic', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(2, 'Trollhide', SETS.CORE2012);
COLLECTION.addCard(1, 'Trumpet Blast', SETS.CONSPIRACYTAKETHECROWN);
COLLECTION.addCard(2, 'Trumpet Blast', SETS.CORE2013);
COLLECTION.addCard(1, 'Trumpet Blast', SETS.KHANSOFTARKIR);
COLLECTION.addCard(6, 'Trusted Forcemage', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Trustworthy Scout', SETS.MODERNHORIZONS);

COLLECTION.addCard(1, 'Tundra Fumarole', SETS.KALDHEIM);
COLLECTION.addCard(2, 'Turn Aside', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(5, 'Turn the Tide', SETS.MIRRODINBESIEGED);
COLLECTION.addCard(2, 'Turn to Slag', SETS.CORE2013);
COLLECTION.addCard(4, 'Turn to Slag', SETS.SCARSOFMIRRODIN);

COLLECTION.addCard(1, 'Twin-Silk Spider', SETS.MODERNHORIZONS);
COLLECTION.addCard(2, 'Twinblade Slasher', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Twins of Maurer Estate', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Twisted Image', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Twitch', SETS.TENTH);

COLLECTION.addCard(1, 'Typhoid Rats', SETS.CORE2015);
COLLECTION.addCard(4, 'Typhoid Rats', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Tyrant of Discord', SETS.AVACYNRESTORED);
