
//collection.addCard(1, 'Example', SETS.EXAMPLE);

collection.addCard(1, 'Valakut Invoker', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Valakut Invoker', SETS.COMMANDERLEGENDS);
collection.addCard(2, 'Valakut Predator', SETS.BATTLEFORZENDIKAR);
collection.addCard(1, 'Valley Dasher', SETS.KHANSOFTARKIR);
collection.addCard(1, 'Vampire Aristocrat', SETS.CORE2010);
collection.addCard(2, 'Vampire Envoy', SETS.OATHOFTHEGATEWATCH);
collection.addCard(1, 'Vampire Nighthawk', SETS.SORINVSINNISTRAD);
collection.addCard(2, 'Vampire Outcasts', SETS.CORE2012);
collection.addCard(3, 'Vampiric Fury', SETS.INNISTRAD);
collection.addCard(8, 'Vanguard\'s Shield', SETS.AVACYNRESTORED);
collection.addCard(2, 'Vanishment', SETS.AVACYNRESTORED);
collection.addCard(3, 'Vapor Snag', SETS.NEWPHYREXIA);
collection.addCard(1, 'Varolz, the Scar-Striped', SETS.DRAGONSMAZE);
collection.addCard(5, 'Vastwood Gorger', SETS.CORE2012);
collection.addCard(2, 'Vastwood Gorger', SETS.CORE2013);
collection.addCard(1, 'Vat Emergence', SETS.ALLWILLBEONE);
collection.addCard(1, 'Vat of Rebirth', SETS.ALLWILLBEONE);
collection.addCard(1, 'Vault Robber', SETS.KALDHEIM);
collection.addCard(1, 'Vault Skyward', SETS.SCARSOFMIRRODIN);

collection.addCard(3, 'Vector Asp', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Vedalken Anatomist', SETS.MIRRODINBESIEGED);
collection.addCard(4, 'Vedalken Certarch', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Vedalken Entrancer', SETS.CORE2013);
collection.addCard(1, 'Vedalken Infuser', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Vega, the Watcher', SETS.KALDHEIM);
collection.addCard(2, 'Veilborn Ghoul', SETS.CORE2013);
collection.addCard(1, 'Vengeful Devil', SETS.MODERNHORIZONS);
collection.addCard(1, 'Venomous Changeling', SETS.MODERNHORIZONS);
collection.addCard(1, 'Venomous Hierophant', SETS.THEROSBEYONDDEATH);
collection.addCard(1, 'Venser\'s Journal', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Verdant Haven', SETS.CORE2014);
collection.addCard(1, 'Vessel of Endless Rest', SETS.AVACYNRESTORED);
collection.addCard(2, 'Vessel of Ephemera', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(4, 'Vessel of Malignity', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Vessel of Nascency', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Vessel of Volatility', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(1, 'Veteran Armorsmith', SETS.CORE2010);
collection.addCard(1, 'Veteran Swordsmith', SETS.CORE2010);
collection.addCard(1, 'Veteran\'s Powerblade', SETS.BROTHERSWAR);
collection.addCard(2, 'Vexing Gull', SETS.THEROSBEYONDDEATH);

collection.addCard(3, 'Viashino Racketeer', SETS.RETURNTORAVNICA);
collection.addCard(1, 'Viashino Sandscout', SETS.TENTH);
collection.addCard(2, 'Viashino Sandsprinter', SETS.MODERNHORIZONS);
collection.addCard(2, 'Vicious Hunger', SETS.EIGHTH);
collection.addCard(1, 'Victim of Night', SETS.BLESSEDVSCURSED);
collection.addCard(3, 'Victim of Night', SETS.INNISTRAD);
collection.addCard(1, 'Victorious Destruction', SETS.NEWPHYREXIA);
collection.addCard(1, 'Vigean Hydropon', SETS.DISSENSION);
collection.addCard(3, 'Vigil for the Lost', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Vile Rebirth', SETS.CORE2013);
collection.addCard(1, 'Village Bell-Ringer', SETS.BLESSEDVSCURSED);
collection.addCard(4, 'Village Bell-Ringer', SETS.INNISTRAD);
collection.addCard(1, 'Village Cannibals', SETS.INNISTRAD);
collection.addCard(2, 'Village Survivors', SETS.DARKASCENSION);
collection.addCard(1, 'Villagers of Estwald', SETS.INNISTRAD);
collection.addCard(1, 'Vineweft', SETS.CORE2015);
collection.addCard(1, 'Violent Impact', SETS.AMONKHET);
collection.addCard(1, 'Viper\'s Kiss', SETS.THEROS);
collection.addCard(2, 'Viridian Claw', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Viridian Revel', SETS.SCARSOFMIRRODIN);
collection.addCard(2, 'Virulent Wound', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Visara the Dreadful', SETS.ETERNALMASTERS);
collection.addCard(1, 'Visions of Beyond', SETS.CORE2012);
collection.addCard(3, 'Vithian Stinger', SETS.SHARDSOFALARA);
collection.addCard(2, 'Vithian Stinger', SETS.SORINVSINNISTRAD);
collection.addCard(4, 'Vivisection', SETS.MIRRODINBESIEGED);
collection.addCard(1, 'Vizkopa Guildmage', SETS.GATECRASH);

collection.addCard(4, 'Voice of the Provinces', SETS.AVACYNRESTORED);
collection.addCard(1, 'Voice of the Provinces', SETS.BLESSEDVSCURSED);
collection.addCard(4, 'Voiceless Spirit', SETS.INNISTRAD);
collection.addCard(2, 'Void Stalker', SETS.CORE2013);
collection.addCard(2, 'Voidwielder', SETS.RETURNTORAVNICA);
collection.addCard(4, 'Volcanic Strength', SETS.CORE2013);
collection.addCard(1, 'Volcanic Submersion', SETS.SHARDSOFALARA);
collection.addCard(3, 'Voldaren Duelist', SETS.SHADOWSOVERINNISTRAD);
collection.addCard(3, 'Volition Reins', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Volt Charge', SETS.ALLWILLBEONE);
collection.addCard(1, 'Volt Charge', SETS.NEWPHYREXIA);
collection.addCard(1, 'Voracious Hatchling', SETS.EVENTIDE);
collection.addCard(1, 'Vorstclaw', SETS.AVACYNRESTORED);
collection.addCard(1, 'Voyage\'s End', SETS.THEROS);
collection.addCard(1, 'Voyaging Satyr', SETS.THEROS);

collection.addCard(3, 'Vraska, Swarm\'s Eminence', SETS.WAROFTHESPARK);

collection.addCard(1, 'Vulshok Berserker', SETS.CORE2011);
collection.addCard(5, 'Vulshok Heartstoker', SETS.SCARSOFMIRRODIN);
collection.addCard(1, 'Vulshok Replica', SETS.SCARSOFMIRRODIN);
collection.addCard(3, 'Vulshok Sorcerer', SETS.FIREANDLIGHTNING);
