
//COLLECTION.addCard(1, 'Example', SETS.EXAMPLE);

COLLECTION.addCard(1, 'Wake of Vultures', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Wake the Reflections', SETS.DRAGONSMAZE);
COLLECTION.addCard(2, 'Wakedancer', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Walker of the Wastes', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(3, 'Walking Corpse', SETS.CORE2013);
COLLECTION.addCard(1, 'Walking Corpse', SETS.WELCOME2016);
COLLECTION.addCard(4, 'Wall of Fire', SETS.CORE2013);
COLLECTION.addCard(1, 'Wall of Omens', SETS.SORINVSINNISTRAD);
COLLECTION.addCard(1, 'Wall of One Thousand Cuts', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Wall of Spears', SETS.DUELSOFTHEPLANESWALKERS);
COLLECTION.addCard(5, 'Wall of Tanglecord', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(5, 'Wall of Torches', SETS.CORE2012);
COLLECTION.addCard(4, 'Wandering Wolf', SETS.AVACYNRESTORED);
COLLECTION.addCard(2, 'War Falcon', SETS.CORE2013);
COLLECTION.addCard(1, 'War Priest of Thune', SETS.CORE2013);
COLLECTION.addCard(2, 'War Report', SETS.NEWPHYREXIA);
COLLECTION.addCard(1, 'Warchanter of Mogis', SETS.BORNOFTHEGODS);
COLLECTION.addCard(2, 'Warclamp Mastiff', SETS.CORE2013);
COLLECTION.addCard(1, 'Ward of Bones', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Warden of Evos Isle', SETS.ETERNALMASTERS);
COLLECTION.addCard(1, 'Warden of Geometries', SETS.OATHOFTHEGATEWATCH);
COLLECTION.addCard(3, 'Warden of the Wall', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Warlord\'s Axe', SETS.CORE2011);
COLLECTION.addCard(4, 'Warpath Ghoul', SETS.CORE2012);
COLLECTION.addCard(2, 'Warped Landscape', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Warteye Witch', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Waste Away', SETS.TORMENT);
COLLECTION.addCard(3, 'Watcher in the Web', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Watercourser', SETS.CORE2013);
COLLECTION.addCard(3, 'Wavecrash Triton', SETS.THEROS);
COLLECTION.addCard(2, 'Wayward Soul', SETS.EXODUS);

COLLECTION.addCard(1, 'Weakness', SETS.CORE2010);
COLLECTION.addCard(1, 'Weakstone\'s Subjugation', SETS.BROTHERSWAR);
COLLECTION.addCard(2, 'Weather the Storm', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Weigh Down', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Weight of the Underworld', SETS.BORNOFTHEGODS);
COLLECTION.addCard(1, 'Welkin Tern', SETS.CORE2013);
COLLECTION.addCard(1, 'Welkin Tern', SETS.CORE2015);
COLLECTION.addCard(2, 'Welkin Tern', SETS.ZENDIKAR);
COLLECTION.addCard(1, 'Werebear', SETS.ETERNALMASTERS);

COLLECTION.addCard(1, 'Whimwader', SETS.SHADOWMOOR);
COLLECTION.addCard(1, 'Whiptail Moloch', SETS.DISSENSION);
COLLECTION.addCard(1, 'Whisper of the Dross', SETS.ALLWILLBEONE);
COLLECTION.addCard(1, 'White Knight', SETS.CORE2010);
COLLECTION.addCard(3, 'Whitesun\'s Passage', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(1, 'Whitesun\'s Passage', SETS.SCARSOFMIRRODIN, true);

COLLECTION.addCard(1, 'Wicker Witch', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(4, 'Wickerbough Elder', SETS.EVENTIDE);
COLLECTION.addCard(2, 'Wight of Precinct Six', SETS.GATECRASH);
COLLECTION.addCard(3, 'Wild Guess', SETS.CORE2013);
COLLECTION.addCard(2, 'Wild Hunger', SETS.DARKASCENSION);
COLLECTION.addCard(5, 'Wilderness Hypnotist', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Wilderness Hypnotist', SETS.EVENTIDE, true);
COLLECTION.addCard(4, 'Wildwood Geist', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Wildwood Rebirth', SETS.GATECRASH);
COLLECTION.addCard(1, 'Wind Drake', SETS.CORE2013);
COLLECTION.addCard(1, 'Wind Drake', SETS.DRAGONSMAZE);
COLLECTION.addCard(1, 'Wind Drake', SETS.EIGHTH);
COLLECTION.addCard(2, 'Winding Way', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Windrider Eel', SETS.ZENDIKAR);
COLLECTION.addCard(1, 'Windstorm', SETS.CORE2010);
COLLECTION.addCard(2, 'Wing Puncture', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(5, 'Wing Shards', SETS.SCOURGE);
COLLECTION.addCard(4, 'Wingcrafter', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Wings of Hubris', SETS.THEROSBEYONDDEATH);
COLLECTION.addCard(1, 'Wings of Velis Vel', SETS.LORWYN);
COLLECTION.addCard(1, 'Wingsteed Rider', SETS.THEROS);
COLLECTION.addCard(3, 'Winter\'s Rest', SETS.MODERNHORIZONS);
COLLECTION.addCard(1, 'Wistful Selkie', SETS.EVENTIDE);
COLLECTION.addCard(1, 'Withercrown', SETS.KALDHEIM);
COLLECTION.addCard(1, 'Withered Wretch', SETS.PLANECHASE);
COLLECTION.addCard(4, 'Withstand Death', SETS.SCARSOFMIRRODIN);
COLLECTION.addCard(2, 'Witness of the Ages', SETS.KHANSOFTARKIR);
COLLECTION.addCard(1, 'Witness of Tomorrows', SETS.THEROSBEYONDDEATH);

COLLECTION.addCard(2, 'Wolfhunter\'s Quiver', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Wolfir Avenger', SETS.AVACYNRESTORED);
COLLECTION.addCard(1, 'Wolfir Silverheart', SETS.AVACYNRESTORED);
COLLECTION.addCard(4, 'Wooden Stake', SETS.INNISTRAD);
COLLECTION.addCard(4, 'Woodland Sleuth', SETS.INNISTRAD);
COLLECTION.addCard(2, 'Woodland Stream', SETS.SHADOWSOVERINNISTRAD);
COLLECTION.addCard(1, 'Worldslayer', SETS.CORE2012);
COLLECTION.addCard(1, 'Wormfang Turtle', SETS.JUDGMENT);
COLLECTION.addCard(1, 'Worn Powerstone', SETS.ETERNALMASTERS);

COLLECTION.addCard(4, 'Wrack with Madness', SETS.DARKASCENSION);
COLLECTION.addCard(1, 'Wrangle', SETS.AETHERREVOLT);
COLLECTION.addCard(1, 'Wrap in Flames', SETS.RISEOFTHEELDRAZI);
COLLECTION.addCard(1, 'Wreath of Geists', SETS.INNISTRAD);
COLLECTION.addCard(3, 'Wring Flesh', SETS.CORE2012);
COLLECTION.addCard(1, 'Wring Flesh', SETS.CORE2014);

COLLECTION.addCard(1, 'Wurm\'s Tooth', SETS.DUELSOFTHEPLANESWALKERS);
