
const HAMSTER = new Deck('Hamster', storage.decks.purple[1]);

HAMSTER.addCard(4, 'Avacyn\'s Pilgrim', SETS.INNISTRAD);
HAMSTER.addCard(1, 'Banefire', SETS.DUELSOFTHEPLANESWALKERS);
HAMSTER.addCard(1, 'Blaze', SETS.DUELSOFTHEPLANESWALKERS);
HAMSTER.addCard(4, 'Bountiful Harvest', SETS.CORE2012);
HAMSTER.addCard(1, 'Crippling Blight', SETS.CORE2015);
HAMSTER.addCard(2, 'Dawntreader Elk', SETS.DARKASCENSION);
HAMSTER.addCard(1, 'Devil\'s Play', SETS.SORINVSINNISTRAD);
HAMSTER.addCard(3, 'Elvish Mystic', SETS.CORE2014);
HAMSTER.addCard(4, 'Farseek', SETS.CORE2013);
HAMSTER.addCard(3, 'Fire Elemental', SETS.CORE2013);
HAMSTER.addCard(1, 'Fireball', SETS.CORE2012);
HAMSTER.addCard(1, 'Forest', SETS.SHADOWSOVERINNISTRAD, false, 296);
HAMSTER.addCard(5, 'Forest', SETS.SHADOWSOVERINNISTRAD, false, 297);
HAMSTER.addCard(4, 'Iron Myr', SETS.SCARSOFMIRRODIN);
HAMSTER.addCard(1, 'Kozilek\'s Channeler', SETS.BATTLEFORZENDIKAR);
HAMSTER.addCard(1, 'Minsc, Beloved Ranger', SETS.ADVENTURESINTHEFORGOTTENREALMS);
HAMSTER.addCard(1, 'Mountain', SETS.CORE2012, false, 243);
HAMSTER.addCard(1, 'Mountain', SETS.CORE2012, false, 244);
HAMSTER.addCard(1, 'Mountain', SETS.INNISTRAD, false, 259);
HAMSTER.addCard(1, 'Mountain', SETS.INNISTRAD, false, 260);
HAMSTER.addCard(1, 'Mountain', SETS.VENSERVSKOTH, false, 74);
HAMSTER.addCard(1, 'Palladium Myr', SETS.SCARSOFMIRRODIN);
HAMSTER.addCard(2, 'Plains', SETS.MIRRODINBESIEGED, false, 146);
HAMSTER.addCard(3, 'Plains', SETS.MIRRODINBESIEGED, false, 147);
HAMSTER.addCard(1, 'Plains', SETS.ZENDIKAR, false, '231a');
HAMSTER.addCard(1, 'Primordial Hydra', SETS.CORE2012);
HAMSTER.addCard(1, 'Pristine Talisman', SETS.NEWPHYREXIA);
HAMSTER.addCard(1, 'Ring of Three Wishes', SETS.CORE2014);
HAMSTER.addCard(1, 'Sakura-Tribe Scout', SETS.SAVIORSOFKAMIGAWA);
HAMSTER.addCard(1, 'Sporemound', SETS.CORE2014);
HAMSTER.addCard(1, 'Swell of Growth', SETS.BATTLEFORZENDIKAR);
HAMSTER.addCard(2, 'Tyrant of Discord', SETS.AVACYNRESTORED);
HAMSTER.addCard(1, 'Undergrowth Champion', SETS.BATTLEFORZENDIKAR);
HAMSTER.addCard(1, 'Worn Powerstone', SETS.ETERNALMASTERS);
HAMSTER.addCard(1, 'Zhur-Taa Druid', SETS.DRAGONSMAZE);
