
const POISON = new Deck('Poison', storage.decks.sapphire[0]);

POISON.addCard(3, 'Blight Mamba', SETS.SCARSOFMIRRODIN);
POISON.addCard(1, 'Blightbelly Rat', SETS.ALLWILLBEONE, false, 289);
POISON.addCard(1, 'Blightbelly Rat', SETS.ALLWILLBEONE, true, 289);
POISON.addCard(2, 'Carrion Call', SETS.SCARSOFMIRRODIN);
POISON.addCard(1, 'Forest', SETS.ALLWILLBEONE, false, 266);
POISON.addCard(1, 'Forest', SETS.BROTHERSWAR, false, 286);
POISON.addCard(1, 'Forest', SETS.CORE2014, false, 247);
POISON.addCard(1, 'Forest', SETS.SHADOWSOVERINNISTRAD, false, 295);
POISON.addCard(2, 'Forest', SETS.THEROS, false, 248);
POISON.addCard(1, 'Golgari Rot Farm', SETS.IZZETVSGOLGARI);
POISON.addCard(2, 'Grafted Exoskeleton', SETS.SCARSOFMIRRODIN);
POISON.addCard(2, 'Gruesome Deformity', SETS.INNISTRAD);
POISON.addCard(1, 'Ichor Rats', SETS.SCARSOFMIRRODIN);
POISON.addCard(2, 'Ichorclaw Myr', SETS.SCARSOFMIRRODIN);
POISON.addCard(1, 'Inkmoth Nexus', SETS.MIRRODINBESIEGED);
POISON.addCard(1, 'Mirrex', SETS.ALLWILLBEONE);
POISON.addCard(1, 'Noxious Assault', SETS.ALLWILLBEONE);
POISON.addCard(2, 'Phyresis', SETS.MIRRODINBESIEGED);
POISON.addCard(1, 'Phyrexian Swarmlord', SETS.NEWPHYREXIA);
POISON.addCard(1, 'Plague Myr', SETS.MIRRODINBESIEGED);
POISON.addCard(4, 'Plague Stinger', SETS.SCARSOFMIRRODIN);
POISON.addCard(2, 'Relic Putrescence', SETS.SCARSOFMIRRODIN);
POISON.addCard(1, 'Septic Rats', SETS.MIRRODINBESIEGED);
POISON.addCard(1, 'Swamp', SETS.CORE2012, false, 239);
POISON.addCard(1, 'Swamp', SETS.CORE2013, false, 239);
POISON.addCard(1, 'Swamp', SETS.INNISTRAD, false, 256);
POISON.addCard(1, 'Swamp', SETS.INNISTRAD, false, 257);
POISON.addCard(1, 'Swamp', SETS.INNISTRAD, false, 258);
POISON.addCard(2, 'Swamp', SETS.RETURNTORAVNICA, false, 264);
POISON.addCard(3, 'Swamp', SETS.SHADOWSOVERINNISTRAD, false, 291);
POISON.addCard(1, 'Swamp', SETS.SORINVSINNISTRAD, false, 37);
POISON.addCard(1, 'Swamp', SETS.THEROS, false, 238);
POISON.addCard(1, 'Swamp', SETS.THEROS, false, 240);
POISON.addCard(1, 'Swamp', SETS.THEROS, false, 241);
POISON.addCard(1, 'Titanic Growth', SETS.CORE2012);
POISON.addCard(1, 'Titanic Growth', SETS.CORE2013);
POISON.addCard(3, 'Tormented Soul', SETS.CORE2012);
POISON.addCard(1, 'Tormented Soul', SETS.CORE2013);
POISON.addCard(1, 'Trigon of Infestation', SETS.SCARSOFMIRRODIN);
